/* Generated by CIL v. 1.7.0 */
/* print_CIL_Input is false */

union _1_main_$node;
struct _IO_FILE;
struct __anonstruct_state_6;
struct timeval;
enum _1_main_$op;
extern void signal(int sig , void *func ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
typedef struct _IO_FILE FILE;
extern int fclose(void *stream ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern void abort() ;
enum _1_main_$op {
    _1_main__constant_unsigned_int$result_STA_0$value_LIT_0 = 108,
    _1_main__local$result_STA_0$value_LIT_0 = 252,
    _1_main__constant_int$result_STA_0$value_LIT_0 = 7,
    _1_main__load_int$left_STA_0$result_STA_0 = 239,
    _1_main__store_void_star$right_STA_0$left_STA_1 = 94,
    _1_main__Ne_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 254,
    _1_main__call$func_LIT_0 = 58,
    _1_main__formal$result_STA_0$value_LIT_0 = 15,
    _1_main__global$result_STA_0$value_LIT_0 = 89,
    _1_main__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1 = 235,
    _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1 = 137,
    _1_main__convert_void_star2void_star$left_STA_0$result_STA_0 = 150,
    _1_main__store_unsigned_int$left_STA_0$right_STA_1 = 60,
    _1_main__constant_void_star$result_STA_0$value_LIT_0 = 191,
    _1_main__store_int$left_STA_0$right_STA_1 = 31,
    _1_main__return_int$expr_STA_0 = 34,
    _1_main__constant_unsigned_long$result_STA_0$value_LIT_0 = 22,
    _1_main__load_void_star$left_STA_0$result_STA_0 = 214,
    _1_main__goto$label_LAB_0 = 55,
    _1_main__convert_int2unsigned_long$left_STA_0$result_STA_0 = 33,
    _1_main__label$label_LAB_0 = 85,
    _1_main__string$result_STA_0$value_LIT_0 = 125,
    _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1 = 233,
    _1_main__IndexPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1 = 132,
    _1_main__branchIfTrue$expr_STA_0$label_LAB_0 = 175
} ;
unsigned char _1_main_$array[1][345]  = { {        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__global$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)24,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__convert_int2unsigned_long$left_STA_0$result_STA_0, 
            _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_main__formal$result_STA_0$value_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__load_void_star$left_STA_0$result_STA_0, 
            _1_main__IndexPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__load_void_star$left_STA_0$result_STA_0,        _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__call$func_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)32,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__store_int$left_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)56,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)32,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__constant_unsigned_int$result_STA_0$value_LIT_0,        (unsigned char)16, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)64,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_unsigned_int$left_STA_0$right_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)2,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)32, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__load_int$left_STA_0$result_STA_0,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__Ne_int_int2int$right_STA_0$result_STA_0$left_STA_1,        _1_main__branchIfTrue$expr_STA_0$label_LAB_0, 
            (unsigned char)9,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__goto$label_LAB_0,        (unsigned char)26,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)72,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__string$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__convert_void_star2void_star$left_STA_0$result_STA_0, 
            _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)3,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)80,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__string$result_STA_0$value_LIT_0,        (unsigned char)24,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__convert_void_star2void_star$left_STA_0$result_STA_0,        _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)88,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__global$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__store_void_star$right_STA_0$left_STA_1, 
            _1_main__call$func_LIT_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)96,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__string$result_STA_0$value_LIT_0,        (unsigned char)27, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__convert_void_star2void_star$left_STA_0$result_STA_0, 
            _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)32,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)104,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_int$left_STA_0$right_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)5,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__return_int$expr_STA_0}};
extern void exit(int status ) ;
extern int raise(int sig ) ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern int rand() ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
void output_i$nit(void) ;
char output[256] ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned long maxlen ) ;
void input_i$nit(void) ;
static int grub_username_get(char *buf , unsigned int buf_size ) ;
extern int gettimeofday(struct timeval *tv , void *tz  , ...) ;
char input[256] ;
void printf_char(char c ) ;
extern int printf(char const   * __restrict  __format  , ...) ;
__inline static int grub_isprint(int c ) ;
struct __anonstruct_state_6 {
   int canary ;
   char buf[16] ;
};
int main(int argc , char **argv ) ;
void megaInit(void) ;
extern unsigned long strlen(char const   *s ) ;
char const   *_1_main_$strings  =    "This gets interesting!\n\000%s\000canary=%08x\n\000";
extern long strtol(char const   *str , char const   *endptr , int base ) ;
union _1_main_$node {
   void *_void_star ;
   unsigned long _unsigned_long ;
   unsigned int _unsigned_int ;
   int _int ;
};
extern unsigned long strnlen(char const   *s , unsigned long maxlen ) ;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern void *memcpy(void *s1 , void const   *s2 , unsigned long size ) ;
void grub_printf(char *str ) ;
extern void *malloc(unsigned long size ) ;
char grub_getkey(void) ;
void my_strcpy(char *dst , char *src ) ;
extern int scanf(char const   *format  , ...) ;
void input_i$nit(void) 
{ 


  {
  input[0] = (char)0;
  input[1] = (char)0;
  input[2] = (char)0;
  input[3] = (char)0;
  input[4] = (char)0;
  input[5] = (char)0;
  input[6] = (char)0;
  input[7] = (char)0;
  input[8] = (char)0;
  input[9] = (char)0;
  input[10] = (char)0;
  input[11] = (char)0;
  input[12] = (char)0;
  input[13] = (char)0;
  input[14] = (char)0;
  input[15] = (char)0;
  input[16] = (char)0;
  input[17] = (char)0;
  input[18] = (char)0;
  input[19] = (char)0;
  input[20] = (char)0;
  input[21] = (char)0;
  input[22] = (char)0;
  input[23] = (char)0;
  input[24] = (char)0;
  input[25] = (char)0;
  input[26] = (char)0;
  input[27] = (char)0;
  input[28] = (char)0;
  input[29] = (char)0;
  input[30] = (char)0;
  input[31] = (char)0;
  input[32] = (char)0;
  input[33] = (char)0;
  input[34] = (char)0;
  input[35] = (char)0;
  input[36] = (char)0;
  input[37] = (char)0;
  input[38] = (char)0;
  input[39] = (char)0;
  input[40] = (char)0;
  input[41] = (char)0;
  input[42] = (char)0;
  input[43] = (char)0;
  input[44] = (char)0;
  input[45] = (char)0;
  input[46] = (char)0;
  input[47] = (char)0;
  input[48] = (char)0;
  input[49] = (char)0;
  input[50] = (char)0;
  input[51] = (char)0;
  input[52] = (char)0;
  input[53] = (char)0;
  input[54] = (char)0;
  input[55] = (char)0;
  input[56] = (char)0;
  input[57] = (char)0;
  input[58] = (char)0;
  input[59] = (char)0;
  input[60] = (char)0;
  input[61] = (char)0;
  input[62] = (char)0;
  input[63] = (char)0;
  input[64] = (char)0;
  input[65] = (char)0;
  input[66] = (char)0;
  input[67] = (char)0;
  input[68] = (char)0;
  input[69] = (char)0;
  input[70] = (char)0;
  input[71] = (char)0;
  input[72] = (char)0;
  input[73] = (char)0;
  input[74] = (char)0;
  input[75] = (char)0;
  input[76] = (char)0;
  input[77] = (char)0;
  input[78] = (char)0;
  input[79] = (char)0;
  input[80] = (char)0;
  input[81] = (char)0;
  input[82] = (char)0;
  input[83] = (char)0;
  input[84] = (char)0;
  input[85] = (char)0;
  input[86] = (char)0;
  input[87] = (char)0;
  input[88] = (char)0;
  input[89] = (char)0;
  input[90] = (char)0;
  input[91] = (char)0;
  input[92] = (char)0;
  input[93] = (char)0;
  input[94] = (char)0;
  input[95] = (char)0;
  input[96] = (char)0;
  input[97] = (char)0;
  input[98] = (char)0;
  input[99] = (char)0;
  input[100] = (char)0;
  input[101] = (char)0;
  input[102] = (char)0;
  input[103] = (char)0;
  input[104] = (char)0;
  input[105] = (char)0;
  input[106] = (char)0;
  input[107] = (char)0;
  input[108] = (char)0;
  input[109] = (char)0;
  input[110] = (char)0;
  input[111] = (char)0;
  input[112] = (char)0;
  input[113] = (char)0;
  input[114] = (char)0;
  input[115] = (char)0;
  input[116] = (char)0;
  input[117] = (char)0;
  input[118] = (char)0;
  input[119] = (char)0;
  input[120] = (char)0;
  input[121] = (char)0;
  input[122] = (char)0;
  input[123] = (char)0;
  input[124] = (char)0;
  input[125] = (char)0;
  input[126] = (char)0;
  input[127] = (char)0;
  input[128] = (char)0;
  input[129] = (char)0;
  input[130] = (char)0;
  input[131] = (char)0;
  input[132] = (char)0;
  input[133] = (char)0;
  input[134] = (char)0;
  input[135] = (char)0;
  input[136] = (char)0;
  input[137] = (char)0;
  input[138] = (char)0;
  input[139] = (char)0;
  input[140] = (char)0;
  input[141] = (char)0;
  input[142] = (char)0;
  input[143] = (char)0;
  input[144] = (char)0;
  input[145] = (char)0;
  input[146] = (char)0;
  input[147] = (char)0;
  input[148] = (char)0;
  input[149] = (char)0;
  input[150] = (char)0;
  input[151] = (char)0;
  input[152] = (char)0;
  input[153] = (char)0;
  input[154] = (char)0;
  input[155] = (char)0;
  input[156] = (char)0;
  input[157] = (char)0;
  input[158] = (char)0;
  input[159] = (char)0;
  input[160] = (char)0;
  input[161] = (char)0;
  input[162] = (char)0;
  input[163] = (char)0;
  input[164] = (char)0;
  input[165] = (char)0;
  input[166] = (char)0;
  input[167] = (char)0;
  input[168] = (char)0;
  input[169] = (char)0;
  input[170] = (char)0;
  input[171] = (char)0;
  input[172] = (char)0;
  input[173] = (char)0;
  input[174] = (char)0;
  input[175] = (char)0;
  input[176] = (char)0;
  input[177] = (char)0;
  input[178] = (char)0;
  input[179] = (char)0;
  input[180] = (char)0;
  input[181] = (char)0;
  input[182] = (char)0;
  input[183] = (char)0;
  input[184] = (char)0;
  input[185] = (char)0;
  input[186] = (char)0;
  input[187] = (char)0;
  input[188] = (char)0;
  input[189] = (char)0;
  input[190] = (char)0;
  input[191] = (char)0;
  input[192] = (char)0;
  input[193] = (char)0;
  input[194] = (char)0;
  input[195] = (char)0;
  input[196] = (char)0;
  input[197] = (char)0;
  input[198] = (char)0;
  input[199] = (char)0;
  input[200] = (char)0;
  input[201] = (char)0;
  input[202] = (char)0;
  input[203] = (char)0;
  input[204] = (char)0;
  input[205] = (char)0;
  input[206] = (char)0;
  input[207] = (char)0;
  input[208] = (char)0;
  input[209] = (char)0;
  input[210] = (char)0;
  input[211] = (char)0;
  input[212] = (char)0;
  input[213] = (char)0;
  input[214] = (char)0;
  input[215] = (char)0;
  input[216] = (char)0;
  input[217] = (char)0;
  input[218] = (char)0;
  input[219] = (char)0;
  input[220] = (char)0;
  input[221] = (char)0;
  input[222] = (char)0;
  input[223] = (char)0;
  input[224] = (char)0;
  input[225] = (char)0;
  input[226] = (char)0;
  input[227] = (char)0;
  input[228] = (char)0;
  input[229] = (char)0;
  input[230] = (char)0;
  input[231] = (char)0;
  input[232] = (char)0;
  input[233] = (char)0;
  input[234] = (char)0;
  input[235] = (char)0;
  input[236] = (char)0;
  input[237] = (char)0;
  input[238] = (char)0;
  input[239] = (char)0;
  input[240] = (char)0;
  input[241] = (char)0;
  input[242] = (char)0;
  input[243] = (char)0;
  input[244] = (char)0;
  input[245] = (char)0;
  input[246] = (char)0;
  input[247] = (char)0;
  input[248] = (char)0;
  input[249] = (char)0;
  input[250] = (char)0;
  input[251] = (char)0;
  input[252] = (char)0;
  input[253] = (char)0;
  input[254] = (char)0;
  input[255] = (char)0;
}
}
void output_i$nit(void) 
{ 


  {
  output[0] = (char)0;
  output[1] = (char)0;
  output[2] = (char)0;
  output[3] = (char)0;
  output[4] = (char)0;
  output[5] = (char)0;
  output[6] = (char)0;
  output[7] = (char)0;
  output[8] = (char)0;
  output[9] = (char)0;
  output[10] = (char)0;
  output[11] = (char)0;
  output[12] = (char)0;
  output[13] = (char)0;
  output[14] = (char)0;
  output[15] = (char)0;
  output[16] = (char)0;
  output[17] = (char)0;
  output[18] = (char)0;
  output[19] = (char)0;
  output[20] = (char)0;
  output[21] = (char)0;
  output[22] = (char)0;
  output[23] = (char)0;
  output[24] = (char)0;
  output[25] = (char)0;
  output[26] = (char)0;
  output[27] = (char)0;
  output[28] = (char)0;
  output[29] = (char)0;
  output[30] = (char)0;
  output[31] = (char)0;
  output[32] = (char)0;
  output[33] = (char)0;
  output[34] = (char)0;
  output[35] = (char)0;
  output[36] = (char)0;
  output[37] = (char)0;
  output[38] = (char)0;
  output[39] = (char)0;
  output[40] = (char)0;
  output[41] = (char)0;
  output[42] = (char)0;
  output[43] = (char)0;
  output[44] = (char)0;
  output[45] = (char)0;
  output[46] = (char)0;
  output[47] = (char)0;
  output[48] = (char)0;
  output[49] = (char)0;
  output[50] = (char)0;
  output[51] = (char)0;
  output[52] = (char)0;
  output[53] = (char)0;
  output[54] = (char)0;
  output[55] = (char)0;
  output[56] = (char)0;
  output[57] = (char)0;
  output[58] = (char)0;
  output[59] = (char)0;
  output[60] = (char)0;
  output[61] = (char)0;
  output[62] = (char)0;
  output[63] = (char)0;
  output[64] = (char)0;
  output[65] = (char)0;
  output[66] = (char)0;
  output[67] = (char)0;
  output[68] = (char)0;
  output[69] = (char)0;
  output[70] = (char)0;
  output[71] = (char)0;
  output[72] = (char)0;
  output[73] = (char)0;
  output[74] = (char)0;
  output[75] = (char)0;
  output[76] = (char)0;
  output[77] = (char)0;
  output[78] = (char)0;
  output[79] = (char)0;
  output[80] = (char)0;
  output[81] = (char)0;
  output[82] = (char)0;
  output[83] = (char)0;
  output[84] = (char)0;
  output[85] = (char)0;
  output[86] = (char)0;
  output[87] = (char)0;
  output[88] = (char)0;
  output[89] = (char)0;
  output[90] = (char)0;
  output[91] = (char)0;
  output[92] = (char)0;
  output[93] = (char)0;
  output[94] = (char)0;
  output[95] = (char)0;
  output[96] = (char)0;
  output[97] = (char)0;
  output[98] = (char)0;
  output[99] = (char)0;
  output[100] = (char)0;
  output[101] = (char)0;
  output[102] = (char)0;
  output[103] = (char)0;
  output[104] = (char)0;
  output[105] = (char)0;
  output[106] = (char)0;
  output[107] = (char)0;
  output[108] = (char)0;
  output[109] = (char)0;
  output[110] = (char)0;
  output[111] = (char)0;
  output[112] = (char)0;
  output[113] = (char)0;
  output[114] = (char)0;
  output[115] = (char)0;
  output[116] = (char)0;
  output[117] = (char)0;
  output[118] = (char)0;
  output[119] = (char)0;
  output[120] = (char)0;
  output[121] = (char)0;
  output[122] = (char)0;
  output[123] = (char)0;
  output[124] = (char)0;
  output[125] = (char)0;
  output[126] = (char)0;
  output[127] = (char)0;
  output[128] = (char)0;
  output[129] = (char)0;
  output[130] = (char)0;
  output[131] = (char)0;
  output[132] = (char)0;
  output[133] = (char)0;
  output[134] = (char)0;
  output[135] = (char)0;
  output[136] = (char)0;
  output[137] = (char)0;
  output[138] = (char)0;
  output[139] = (char)0;
  output[140] = (char)0;
  output[141] = (char)0;
  output[142] = (char)0;
  output[143] = (char)0;
  output[144] = (char)0;
  output[145] = (char)0;
  output[146] = (char)0;
  output[147] = (char)0;
  output[148] = (char)0;
  output[149] = (char)0;
  output[150] = (char)0;
  output[151] = (char)0;
  output[152] = (char)0;
  output[153] = (char)0;
  output[154] = (char)0;
  output[155] = (char)0;
  output[156] = (char)0;
  output[157] = (char)0;
  output[158] = (char)0;
  output[159] = (char)0;
  output[160] = (char)0;
  output[161] = (char)0;
  output[162] = (char)0;
  output[163] = (char)0;
  output[164] = (char)0;
  output[165] = (char)0;
  output[166] = (char)0;
  output[167] = (char)0;
  output[168] = (char)0;
  output[169] = (char)0;
  output[170] = (char)0;
  output[171] = (char)0;
  output[172] = (char)0;
  output[173] = (char)0;
  output[174] = (char)0;
  output[175] = (char)0;
  output[176] = (char)0;
  output[177] = (char)0;
  output[178] = (char)0;
  output[179] = (char)0;
  output[180] = (char)0;
  output[181] = (char)0;
  output[182] = (char)0;
  output[183] = (char)0;
  output[184] = (char)0;
  output[185] = (char)0;
  output[186] = (char)0;
  output[187] = (char)0;
  output[188] = (char)0;
  output[189] = (char)0;
  output[190] = (char)0;
  output[191] = (char)0;
  output[192] = (char)0;
  output[193] = (char)0;
  output[194] = (char)0;
  output[195] = (char)0;
  output[196] = (char)0;
  output[197] = (char)0;
  output[198] = (char)0;
  output[199] = (char)0;
  output[200] = (char)0;
  output[201] = (char)0;
  output[202] = (char)0;
  output[203] = (char)0;
  output[204] = (char)0;
  output[205] = (char)0;
  output[206] = (char)0;
  output[207] = (char)0;
  output[208] = (char)0;
  output[209] = (char)0;
  output[210] = (char)0;
  output[211] = (char)0;
  output[212] = (char)0;
  output[213] = (char)0;
  output[214] = (char)0;
  output[215] = (char)0;
  output[216] = (char)0;
  output[217] = (char)0;
  output[218] = (char)0;
  output[219] = (char)0;
  output[220] = (char)0;
  output[221] = (char)0;
  output[222] = (char)0;
  output[223] = (char)0;
  output[224] = (char)0;
  output[225] = (char)0;
  output[226] = (char)0;
  output[227] = (char)0;
  output[228] = (char)0;
  output[229] = (char)0;
  output[230] = (char)0;
  output[231] = (char)0;
  output[232] = (char)0;
  output[233] = (char)0;
  output[234] = (char)0;
  output[235] = (char)0;
  output[236] = (char)0;
  output[237] = (char)0;
  output[238] = (char)0;
  output[239] = (char)0;
  output[240] = (char)0;
  output[241] = (char)0;
  output[242] = (char)0;
  output[243] = (char)0;
  output[244] = (char)0;
  output[245] = (char)0;
  output[246] = (char)0;
  output[247] = (char)0;
  output[248] = (char)0;
  output[249] = (char)0;
  output[250] = (char)0;
  output[251] = (char)0;
  output[252] = (char)0;
  output[253] = (char)0;
  output[254] = (char)0;
  output[255] = (char)0;
}
}
static int grub_username_get(char *buf , unsigned int buf_size ) 
{ 
  unsigned int cur_len ;
  int key ;
  char tmp ;
  int tmp___0 ;
  unsigned int tmp___1 ;

  {
  cur_len = 0U;
  while (1) {
    tmp = grub_getkey();
    key = (int )tmp;
    if (key == 10) {
      break;
    } else
    if (key == 13) {
      break;
    }
    if (key == 27) {
      cur_len = 0U;
      break;
    }
    if (key == 8) {
      cur_len --;
      grub_printf((char *)"\b");
      continue;
    }
    tmp___0 = grub_isprint(key);
    if (! tmp___0) {
      continue;
    }
    if (cur_len + 2U < buf_size) {
      tmp___1 = cur_len;
      cur_len ++;
      *(buf + tmp___1) = (char )key;
      printf_char((char )key);
    }
  }
  grub_printf((char *)"\n");
  return (key != 27);
}
}
void my_strcpy(char *dst , char *src ) 
{ 
  int i ;
  char tmp ;

  {
  i = 0;
  while (1) {
    tmp = *(src + i);
    *(dst + i) = tmp;
    if (! tmp) {
      break;
    }
    i ++;
  }
  return;
}
}
int main(int argc , char **argv ) 
{ 
  char _1_main_$locals[108] ;
  union _1_main_$node _1_main_$stack[1][32] ;
  union _1_main_$node *_1_main_$sp[1] ;
  unsigned char *_1_main_$pc[1] ;

  {
  megaInit();
  _1_main_$sp[0] = _1_main_$stack[0];
  _1_main_$pc[0] = _1_main_$array[0];
  while (1) {
    switch (*(_1_main_$pc[0])) {
    case _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_void_star = (_1_main_$sp[0] + 0)->_void_star + (_1_main_$sp[0] + -1)->_unsigned_long;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__constant_void_star$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_void_star = *((void **)_1_main_$pc[0]);
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 8;
    break;
    case _1_main__goto$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    _1_main_$pc[0] += *((int *)_1_main_$pc[0]);
    break;
    case _1_main__store_int$left_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    *((int *)(_1_main_$sp[0] + 0)->_void_star) = (_1_main_$sp[0] + -1)->_int;
    _1_main_$sp[0] += -2;
    break;
    case _1_main__IndexPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_void_star = (_1_main_$sp[0] + 0)->_void_star + (_1_main_$sp[0] + -1)->_unsigned_long;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__label$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    break;
    case _1_main__local$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_void_star = (void *)(_1_main_$locals + *((int *)_1_main_$pc[0]));
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__global$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    switch (*((int *)_1_main_$pc[0])) {
    case 1: 
    (_1_main_$sp[0] + 1)->_void_star = (void *)(output);
    break;
    case 0: 
    (_1_main_$sp[0] + 1)->_void_star = (void *)(input);
    break;
    }
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_void_star = (_1_main_$sp[0] + 0)->_void_star + (_1_main_$sp[0] + -1)->_int;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__store_void_star$right_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    *((void **)(_1_main_$sp[0] + -1)->_void_star) = (_1_main_$sp[0] + 0)->_void_star;
    _1_main_$sp[0] += -2;
    break;
    case _1_main__load_int$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_int = *((int *)(_1_main_$sp[0] + 0)->_void_star);
    break;
    case _1_main__constant_unsigned_int$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_unsigned_int = *((unsigned int *)_1_main_$pc[0]);
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__convert_int2unsigned_long$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_unsigned_long = (unsigned long )(_1_main_$sp[0] + 0)->_int;
    break;
    case _1_main__Ne_int_int2int$right_STA_0$result_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_int = (_1_main_$sp[0] + -1)->_int != (_1_main_$sp[0] + 0)->_int;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__formal$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    switch (*((int *)_1_main_$pc[0])) {
    case 1: 
    (_1_main_$sp[0] + 1)->_void_star = (void *)(& argv);
    break;
    case 0: 
    (_1_main_$sp[0] + 1)->_void_star = (void *)(& argc);
    break;
    }
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__return_int$expr_STA_0: 
    (_1_main_$pc[0]) ++;
    return ((_1_main_$sp[0] + 0)->_int);
    break;
    case _1_main__convert_void_star2void_star$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_void_star = (_1_main_$sp[0] + 0)->_void_star;
    break;
    case _1_main__store_unsigned_int$left_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    *((unsigned int *)(_1_main_$sp[0] + 0)->_void_star) = (_1_main_$sp[0] + -1)->_unsigned_int;
    _1_main_$sp[0] += -2;
    break;
    case _1_main__load_void_star$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_void_star = *((void **)(_1_main_$sp[0] + 0)->_void_star);
    break;
    case _1_main__constant_int$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_int = *((int *)_1_main_$pc[0]);
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__constant_unsigned_long$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_unsigned_long = *((unsigned long *)_1_main_$pc[0]);
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 8;
    break;
    case _1_main__string$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_void_star = (void *)(_1_main_$strings + *((int *)_1_main_$pc[0]));
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__call$func_LIT_0: 
    (_1_main_$pc[0]) ++;
    switch (*((int *)_1_main_$pc[0])) {
    case 1: 
    my_strcpy(*((char **)(_1_main_$locals + 16)), *((char **)(_1_main_$locals + 24)));
    break;
    case 2: 
    grub_username_get(*((char **)(_1_main_$locals + 56)), *((unsigned int *)(_1_main_$locals + 64)));
    break;
    case 3: 
    printf(*((char const   * __restrict  *)(_1_main_$locals + 72)));
    break;
    case 5: 
    printf(*((char const   * __restrict  *)(_1_main_$locals + 96)), *((int *)(_1_main_$locals + 104)));
    break;
    case 4: 
    printf(*((char const   * __restrict  *)(_1_main_$locals + 80)), *((char **)(_1_main_$locals + 88)));
    break;
    }
    _1_main_$pc[0] += 4;
    break;
    case _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_unsigned_long = (_1_main_$sp[0] + -1)->_unsigned_long * (_1_main_$sp[0] + 0)->_unsigned_long;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__branchIfTrue$expr_STA_0$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    if ((_1_main_$sp[0] + 0)->_int) {
      _1_main_$pc[0] += *((int *)_1_main_$pc[0]);
    } else {
      _1_main_$pc[0] += 4;
    }
    (_1_main_$sp[0]) --;
    break;
    }
  }
}
}
void printf_char(char c ) 
{ 
  char buf[2] ;

  {
  buf[0] = c;
  buf[1] = (char)0;
  grub_printf(buf);
  return;
}
}
void grub_printf(char *str ) 
{ 
  static int p  = 0;
  int i ;
  char tmp ;

  {
  i = 0;
  while (1) {
    tmp = *(str + i);
    output[p] = tmp;
    if (! tmp) {
      break;
    }
    p ++;
    i ++;
  }
  return;
}
}
void megaInit(void) 
{ 


  {
  output_i$nit();
  input_i$nit();
}
}
__inline static int grub_isprint(int c ) 
{ 
  int tmp ;

  {
  if (c >= 32) {
    if (c <= 126) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
char grub_getkey(void) 
{ 
  static int p  = 0;
  char k ;
  int tmp ;

  {
  tmp = p;
  p ++;
  k = input[tmp];
  if ((int )k == 0) {
    return ((char )'\n');
  }
  return ((char)0);
}
}
