/* Generated by CIL v. 1.7.0 */
/* print_CIL_Input is false */

struct XXH32_state_s;
struct XXH64_state_s;
struct _IO_FILE;
enum _1_main_$op;
enum __anonenum_XXH_endianess_28;
struct XXH64_state_s;
union _1_main_$node;
struct __anonstruct_XXH32_canonical_t_26;
enum __anonenum_XXH_alignment_29;
enum __anonenum_XXH_errorcode_25;
struct XXH32_state_s;
struct __anonstruct_XXH64_canonical_t_27;
struct timeval;
enum __anonenum_XXH_alignment_29 {
    XXH_aligned = 0,
    XXH_unaligned = 1
} ;
enum __anonenum_XXH_endianess_28 {
    XXH_bigEndian = 0,
    XXH_littleEndian = 1
} ;
typedef unsigned int __uint32_t;
typedef __uint32_t uint32_t;
typedef uint32_t U32;
typedef enum __anonenum_XXH_alignment_29 XXH_alignment;
typedef enum __anonenum_XXH_endianess_28 XXH_endianess;
__inline static U32 ( __attribute__((__always_inline__)) XXH_readLE32_align)(void const   *ptr ,
                                                                             XXH_endianess endian ,
                                                                             XXH_alignment align ) ;
void PRIME32_4_i$nit(void) ;
typedef unsigned long __uint64_t;
typedef __uint64_t uint64_t;
typedef uint64_t U64;
typedef struct XXH64_state_s XXH64_state_t;
__inline static U64 ( __attribute__((__always_inline__)) XXH64_digest_endian)(XXH64_state_t const   *state ,
                                                                              XXH_endianess endian ) ;
typedef enum __anonenum_XXH_errorcode_25 XXH_errorcode;
typedef unsigned long size_t;
__inline static XXH_errorcode ( __attribute__((__always_inline__)) XXH64_update_endian)(XXH64_state_t *state ,
                                                                                        void const   *input ,
                                                                                        size_t len ,
                                                                                        XXH_endianess endian ) ;
static U64 XXH_readBE64(void const   *ptr ) ;
__inline static U64 ( __attribute__((__always_inline__)) XXH64_endian_align)(void const   *input ,
                                                                             size_t len ,
                                                                             U64 seed ,
                                                                             XXH_endianess endian ,
                                                                             XXH_alignment align ) ;
extern void exit(int status ) ;
unsigned int XXH_versionNumber(void) ;
__inline static U64 ( __attribute__((__always_inline__)) XXH_readLE64)(void const   *ptr ,
                                                                       XXH_endianess endian ) ;
typedef struct XXH32_state_s XXH32_state_t;
XXH_errorcode XXH32_update(XXH32_state_t *state_in , void const   *input , size_t len ) ;
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
static void *XXH_malloc(size_t s ) ;
XXH_errorcode XXH64_freeState(XXH64_state_t *statePtr ) ;
typedef struct _IO_FILE FILE;
extern void signal(int sig , void *func ) ;
typedef struct __anonstruct_XXH64_canonical_t_27 XXH64_canonical_t;
typedef unsigned long long XXH64_hash_t;
void XXH64_canonicalFromHash(XXH64_canonical_t *dst , XXH64_hash_t hash ) ;
void PRIME64_3_i$nit(void) ;
unsigned int XXH32(void const   *input , size_t len , unsigned int seed ) ;
void XXH64_copyState(XXH64_state_t *dstState , XXH64_state_t const   *srcState ) ;
__inline static U32 ( __attribute__((__always_inline__)) XXH32_endian_align)(void const   *input ,
                                                                             size_t len ,
                                                                             U32 seed ,
                                                                             XXH_endianess endian ,
                                                                             XXH_alignment align ) ;
void PRIME32_5_i$nit(void) ;
enum _1_main_$op {
    _1_main__local$result_STA_0$value_LIT_0 = 252,
    _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1 = 60,
    _1_main__label$label_LAB_0 = 85,
    _1_main__load_void_star$left_STA_0$result_STA_0 = 22,
    _1_main__convert_void_star2void_star$left_STA_0$result_STA_0 = 239,
    _1_main__convert_int2unsigned_long$left_STA_0$result_STA_0 = 108,
    _1_main__constant_unsigned_long$result_STA_0$value_LIT_0 = 125,
    _1_main__Eq_unsigned_long_unsigned_long2int$left_STA_0$result_STA_0$right_STA_1 = 94,
    _1_main__string$result_STA_0$value_LIT_0 = 235,
    _1_main__convert_int2void_star$left_STA_0$result_STA_0 = 137,
    _1_main__branchIfTrue$expr_STA_0$label_LAB_0 = 191,
    _1_main__IndexPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1 = 175,
    _1_main__return_int$expr_STA_0 = 34,
    _1_main__store_void_star$left_STA_0$right_STA_1 = 31,
    _1_main__Lt_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 214,
    _1_main__constant_int$result_STA_0$value_LIT_0 = 7,
    _1_main__store_unsigned_long$right_STA_0$left_STA_1 = 89,
    _1_main__load_unsigned_long$left_STA_0$result_STA_0 = 150,
    _1_main__formal$result_STA_0$value_LIT_0 = 254,
    _1_main__load_int$left_STA_0$result_STA_0 = 132,
    _1_main__call$func_LIT_0 = 58,
    _1_main__store_int$left_STA_0$right_STA_1 = 233,
    _1_main__goto$label_LAB_0 = 55
} ;
XXH_errorcode XXH32_reset(XXH32_state_t *statePtr , unsigned int seed ) ;
void PRIME32_1_i$nit(void) ;
static int g_one ;
typedef struct __anonstruct_XXH32_canonical_t_26 XXH32_canonical_t;
typedef unsigned int XXH32_hash_t;
XXH32_hash_t XXH32_hashFromCanonical(XXH32_canonical_t const   *src ) ;
static U32 XXH_read32(void const   *memPtr ) ;
__inline static U64 ( __attribute__((__always_inline__)) XXH_readLE64_align)(void const   *ptr ,
                                                                             XXH_endianess endian ,
                                                                             XXH_alignment align ) ;
struct XXH64_state_s {
   unsigned long long total_len ;
   unsigned long long v1 ;
   unsigned long long v2 ;
   unsigned long long v3 ;
   unsigned long long v4 ;
   unsigned long long mem64[4] ;
   unsigned int memsize ;
   unsigned int reserved[2] ;
};
static unsigned int PRIME32_5 ;
static unsigned int PRIME32_4 ;
static unsigned int PRIME32_3 ;
static unsigned int PRIME32_2 ;
static unsigned int PRIME32_1 ;
unsigned long SECRET(unsigned long input ) ;
enum __anonenum_XXH_errorcode_25 {
    XXH_OK = 0,
    XXH_ERROR = 1
} ;
void PRIME64_4_i$nit(void) ;
extern int printf(char const   * __restrict  __format  , ...) ;
static U32 XXH32_round(U32 seed , U32 input ) ;
static unsigned long PRIME64_5 ;
extern void abort() ;
static unsigned long PRIME64_4 ;
static unsigned long PRIME64_3 ;
static unsigned long PRIME64_2 ;
static void XXH_free(void *p ) ;
static unsigned long PRIME64_1 ;
void XXH32_canonicalFromHash(XXH32_canonical_t *dst , XXH32_hash_t hash ) ;
void PRIME32_2_i$nit(void) ;
unsigned int XXH32_digest(XXH32_state_t const   *state_in ) ;
static U32 XXH_readBE32(void const   *ptr ) ;
typedef unsigned char __uint8_t;
__inline static XXH_errorcode ( __attribute__((__always_inline__)) XXH32_update_endian)(XXH32_state_t *state ,
                                                                                        void const   *input ,
                                                                                        size_t len ,
                                                                                        XXH_endianess endian ) ;
int main(int argc , char **argv ) ;
extern unsigned long strlen(char const   *s ) ;
XXH_errorcode XXH32_freeState(XXH32_state_t *statePtr ) ;
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) free)(void *__ptr ) ;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
unsigned char _1_main_$array[1][262]  = { {        _1_main__formal$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)2, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__Lt_int_int2int$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)32,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__string$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__convert_void_star2void_star$left_STA_0$result_STA_0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_void_star$left_STA_0$right_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__return_int$expr_STA_0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)8, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_main__formal$result_STA_0$value_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__load_void_star$left_STA_0$result_STA_0, 
            _1_main__IndexPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__load_void_star$left_STA_0$result_STA_0,        _1_main__convert_void_star2void_star$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)24,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_void_star$left_STA_0$right_STA_1,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__convert_int2void_star$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)32,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_void_star$left_STA_0$right_STA_1,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)10,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)40, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1, 
            _1_main__call$func_LIT_0,        (unsigned char)2,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)48,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)56, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__load_unsigned_long$left_STA_0$result_STA_0, 
            _1_main__store_unsigned_long$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)64,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)48, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__load_unsigned_long$left_STA_0$result_STA_0, 
            _1_main__store_unsigned_long$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)72,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)64, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__load_unsigned_long$left_STA_0$result_STA_0, 
            _1_main__store_unsigned_long$right_STA_0$left_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)3,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)80, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)88,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_unsigned_long$left_STA_0$result_STA_0,        _1_main__store_unsigned_long$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)96, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)80,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_unsigned_long$left_STA_0$result_STA_0,        _1_main__store_unsigned_long$right_STA_0$left_STA_1,        _1_main__string$result_STA_0$value_LIT_0,        (unsigned char)36, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__convert_void_star2void_star$left_STA_0$result_STA_0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)104,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_void_star$left_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)112, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)96,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_unsigned_long$left_STA_0$result_STA_0,        _1_main__store_unsigned_long$right_STA_0$left_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)14,        (unsigned char)197,        (unsigned char)42, 
            (unsigned char)106,        (unsigned char)239,        (unsigned char)122,        (unsigned char)157, 
            (unsigned char)158,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)96,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_unsigned_long$left_STA_0$result_STA_0,        _1_main__Eq_unsigned_long_unsigned_long2int$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)26,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__string$result_STA_0$value_LIT_0,        (unsigned char)41, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__convert_void_star2void_star$left_STA_0$result_STA_0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)120,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_void_star$left_STA_0$right_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)5, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__return_int$expr_STA_0}};
extern int gettimeofday(struct timeval *tv ,
                        void *tz  , ...) ;
__inline static U32 ( __attribute__((__always_inline__)) XXH_readLE32)(void const   *ptr ,
                                                                       XXH_endianess endian ) ;
XXH_errorcode XXH64_reset(XXH64_state_t *statePtr , unsigned long long seed ) ;
static U64 XXH64_mergeRound(U64 acc , U64 val ) ;
void XXH32_copyState(XXH32_state_t *dstState , XXH32_state_t const   *srcState ) ;
void PRIME64_5_i$nit(void) ;
unsigned long long XXH64_digest(XXH64_state_t const   *state_in ) ;
unsigned long long XXH64(void const   *input , size_t len , unsigned long long seed ) ;
void g_one_i$nit(void) ;
extern int raise(int sig ) ;
void megaInit(void) ;
void PRIME64_1_i$nit(void) ;
extern  __attribute__((__nothrow__)) unsigned long ( __attribute__((__nonnull__(1),
__leaf__)) strtoul)(char const   * __restrict  __nptr , char ** __restrict  __endptr ,
                    int __base ) ;
XXH64_hash_t XXH64_hashFromCanonical(XXH64_canonical_t const   *src ) ;
char const   *_1_main_$strings  =    "Call this program with 1 arguments\n\000%lu\n\000Success!\n\000";
void PRIME32_3_i$nit(void) ;
static U64 XXH_read64(void const   *memPtr ) ;
static U64 XXH64_round(U64 acc , U64 input ) ;
__inline static U32 ( __attribute__((__always_inline__)) XXH32_digest_endian)(XXH32_state_t const   *state ,
                                                                              XXH_endianess endian ) ;
XXH32_state_t *XXH32_createState(void) ;
typedef __uint8_t uint8_t;
XXH64_state_t *XXH64_createState(void) ;
extern int rand() ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned long maxlen ) ;
union _1_main_$node {
   void *_void_star ;
   unsigned long _unsigned_long ;
   int _int ;
};
extern  __attribute__((__nothrow__)) void *( __attribute__((__nonnull__(1), __leaf__)) memset)(void *__s ,
                                                                                               int __c ,
                                                                                               size_t __n ) ;
struct __anonstruct_XXH64_canonical_t_27 {
   unsigned char digest[8] ;
};
extern long strtol(char const   *str , char const   *endptr , int base ) ;
struct __anonstruct_XXH32_canonical_t_26 {
   unsigned char digest[4] ;
};
extern void *fopen(char const   *filename , char const   *mode ) ;
extern int scanf(char const   *format  , ...) ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern int fclose(void *stream ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
typedef uint8_t BYTE;
extern double strtod(char const   *str , char const   *endptr ) ;
struct XXH32_state_s {
   unsigned int total_len_32 ;
   unsigned int large_len ;
   unsigned int v1 ;
   unsigned int v2 ;
   unsigned int v3 ;
   unsigned int v4 ;
   unsigned int mem32[4] ;
   unsigned int memsize ;
   unsigned int reserved ;
};
void PRIME64_2_i$nit(void) ;
extern  __attribute__((__nothrow__)) void *( __attribute__((__nonnull__(1,2), __leaf__)) memcpy)(void * __restrict  __dest ,
                                                                                                 void const   * __restrict  __src ,
                                                                                                 size_t __n ) ;
XXH_errorcode XXH64_update(XXH64_state_t *state_in , void const   *input , size_t len ) ;
extern unsigned long strnlen(char const   *s , unsigned long maxlen ) ;
static void *XXH_memcpy(void *dest , void const   *src , size_t size ) ;
XXH_errorcode XXH64_update(XXH64_state_t *state_in , void const   *input , size_t len ) 
{ 
  XXH_endianess endian_detected ;
  XXH_errorcode tmp ;
  XXH_errorcode tmp___0 ;

  {
  endian_detected = (XXH_endianess )*((char const   *)(& g_one));
  if ((unsigned int )endian_detected == 1U) {
    tmp = XXH64_update_endian(state_in, input, len, (XXH_endianess )1);
    return (tmp);
  } else {
    tmp___0 = XXH64_update_endian(state_in, input, len, (XXH_endianess )0);
    return (tmp___0);
  }
}
}
void PRIME32_4_i$nit(void) 
{ 


  {
  PRIME32_4 = (U32 const   )668265263U;
}
}
static U64 XXH_read64(void const   *memPtr ) 
{ 
  U64 val ;

  {
  memcpy((void */* __restrict  */)(& val), (void const   */* __restrict  */)memPtr,
         sizeof(val));
  return (val);
}
}
XXH_errorcode XXH32_reset(XXH32_state_t *statePtr , unsigned int seed ) 
{ 
  XXH32_state_t state ;

  {
  memset((void *)(& state), 0, sizeof(state));
  state.v1 = (seed + (unsigned int )PRIME32_1) + (unsigned int )PRIME32_2;
  state.v2 = seed + (unsigned int )PRIME32_2;
  state.v3 = seed;
  state.v4 = seed - (unsigned int )PRIME32_1;
  memcpy((void */* __restrict  */)statePtr, (void const   */* __restrict  */)(& state),
         sizeof(state) - sizeof(state.reserved));
  return ((XXH_errorcode )0);
}
}
unsigned int XXH32_digest(XXH32_state_t const   *state_in ) 
{ 
  XXH_endianess endian_detected ;
  U32 tmp ;
  U32 tmp___0 ;

  {
  endian_detected = (XXH_endianess )*((char const   *)(& g_one));
  if ((unsigned int )endian_detected == 1U) {
    tmp = XXH32_digest_endian(state_in, (XXH_endianess )1);
    return (tmp);
  } else {
    tmp___0 = XXH32_digest_endian(state_in, (XXH_endianess )0);
    return (tmp___0);
  }
}
}
__inline static U32 ( __attribute__((__always_inline__)) XXH32_endian_align)(void const   *input ,
                                                                             size_t len ,
                                                                             U32 seed ,
                                                                             XXH_endianess endian ,
                                                                             XXH_alignment align ) 
{ 
  BYTE const   *p ;
  BYTE const   *bEnd ;
  U32 h32 ;
  BYTE const   *limit ;
  U32 v1 ;
  U32 v2 ;
  U32 v3 ;
  U32 v4 ;
  U32 tmp ;
  U32 tmp___0 ;
  U32 tmp___1 ;
  U32 tmp___2 ;
  U32 tmp___3 ;

  {
  p = (BYTE const   *)input;
  bEnd = p + len;
  if (len >= 16UL) {
    limit = bEnd - 16;
    v1 = (seed + (U32 )PRIME32_1) + (U32 )PRIME32_2;
    v2 = seed + (U32 )PRIME32_2;
    v3 = seed;
    v4 = seed - (U32 )PRIME32_1;
    while (1) {
      tmp = XXH_readLE32_align((void const   *)p, endian, align);
      v1 = XXH32_round(v1, tmp);
      p += 4;
      tmp___0 = XXH_readLE32_align((void const   *)p, endian, align);
      v2 = XXH32_round(v2, tmp___0);
      p += 4;
      tmp___1 = XXH_readLE32_align((void const   *)p, endian, align);
      v3 = XXH32_round(v3, tmp___1);
      p += 4;
      tmp___2 = XXH_readLE32_align((void const   *)p, endian, align);
      v4 = XXH32_round(v4, tmp___2);
      p += 4;
      if (! ((unsigned long )p <= (unsigned long )limit)) {
        break;
      }
    }
    h32 = ((((v1 << 1) | (v1 >> 31)) + ((v2 << 7) | (v2 >> 25))) + ((v3 << 12) | (v3 >> 20))) + ((v4 << 18) | (v4 >> 14));
  } else {
    h32 = seed + (U32 )PRIME32_5;
  }
  h32 += (U32 )len;
  while ((unsigned long )(p + 4) <= (unsigned long )bEnd) {
    tmp___3 = XXH_readLE32_align((void const   *)p, endian, align);
    h32 += tmp___3 * (U32 )PRIME32_3;
    h32 = ((h32 << 17) | (h32 >> 15)) * (unsigned int )PRIME32_4;
    p += 4;
  }
  while ((unsigned long )p < (unsigned long )bEnd) {
    h32 += (U32 )((unsigned int const   )*p * PRIME32_5);
    h32 = ((h32 << 11) | (h32 >> 21)) * (unsigned int )PRIME32_1;
    p ++;
  }
  h32 ^= h32 >> 15;
  h32 *= (U32 )PRIME32_2;
  h32 ^= h32 >> 13;
  h32 *= (U32 )PRIME32_3;
  h32 ^= h32 >> 16;
  return (h32);
}
}
XXH_errorcode XXH32_freeState(XXH32_state_t *statePtr ) 
{ 


  {
  XXH_free((void *)statePtr);
  return ((XXH_errorcode )0);
}
}
static U64 XXH64_round(U64 acc , U64 input ) 
{ 


  {
  acc += input * (U64 )PRIME64_2;
  acc = (acc << 31) | (acc >> 33);
  acc *= (U64 )PRIME64_1;
  return (acc);
}
}
static U64 XXH_readBE64(void const   *ptr ) 
{ 
  U64 tmp ;
  long tmp___0 ;
  U64 tmp___1 ;
  U64 tmp___2 ;

  {
  if (*((char const   *)(& g_one))) {
    tmp = XXH_read64(ptr);
    tmp___0 = __builtin_bswap64((long )tmp);
    tmp___2 = (U64 )tmp___0;
  } else {
    tmp___1 = XXH_read64(ptr);
    tmp___2 = tmp___1;
  }
  return (tmp___2);
}
}
static U32 XXH_read32(void const   *memPtr ) 
{ 
  U32 val ;

  {
  memcpy((void */* __restrict  */)(& val), (void const   */* __restrict  */)memPtr,
         sizeof(val));
  return (val);
}
}
unsigned int XXH_versionNumber(void) 
{ 


  {
  return (603U);
}
}
XXH64_hash_t XXH64_hashFromCanonical(XXH64_canonical_t const   *src ) 
{ 
  U64 tmp ;

  {
  tmp = XXH_readBE64((void const   *)src);
  return ((XXH64_hash_t )tmp);
}
}
unsigned long SECRET(unsigned long input ) 
{ 
  unsigned long long seed ;
  unsigned long long hash ;
  unsigned long long tmp ;

  {
  seed = 0ULL;
  tmp = XXH64((void const   *)(& input), sizeof(input), seed);
  hash = tmp;
  return ((unsigned long )hash);
}
}
XXH64_state_t *XXH64_createState(void) 
{ 
  void *tmp ;

  {
  tmp = XXH_malloc(sizeof(XXH64_state_t ));
  return ((XXH64_state_t *)tmp);
}
}
__inline static XXH_errorcode ( __attribute__((__always_inline__)) XXH64_update_endian)(XXH64_state_t *state ,
                                                                                        void const   *input ,
                                                                                        size_t len ,
                                                                                        XXH_endianess endian ) 
{ 
  BYTE const   *p ;
  BYTE const   *bEnd ;
  U64 tmp ;
  U64 tmp___0 ;
  U64 tmp___1 ;
  U64 tmp___2 ;
  U64 tmp___3 ;
  U64 tmp___4 ;
  U64 tmp___5 ;
  U64 tmp___6 ;
  BYTE const   *limit ;
  U64 v1 ;
  U64 v2 ;
  U64 v3 ;
  U64 v4 ;
  U64 tmp___7 ;
  U64 tmp___8 ;
  U64 tmp___9 ;
  U64 tmp___10 ;

  {
  p = (BYTE const   *)input;
  bEnd = p + len;
  if ((unsigned long )input == (unsigned long )((void *)0)) {
    return ((XXH_errorcode )1);
  }
  state->total_len += (unsigned long long )len;
  if ((size_t )state->memsize + len < 32UL) {
    XXH_memcpy((void *)((BYTE *)(state->mem64) + state->memsize), input, len);
    state->memsize += (U32 )len;
    return ((XXH_errorcode )0);
  }
  if (state->memsize) {
    XXH_memcpy((void *)((BYTE *)(state->mem64) + state->memsize), input, (size_t )(32U - state->memsize));
    tmp = XXH_readLE64((void const   *)(state->mem64 + 0), endian);
    tmp___0 = XXH64_round((U64 )state->v1, tmp);
    state->v1 = (unsigned long long )tmp___0;
    tmp___1 = XXH_readLE64((void const   *)(state->mem64 + 1), endian);
    tmp___2 = XXH64_round((U64 )state->v2, tmp___1);
    state->v2 = (unsigned long long )tmp___2;
    tmp___3 = XXH_readLE64((void const   *)(state->mem64 + 2), endian);
    tmp___4 = XXH64_round((U64 )state->v3, tmp___3);
    state->v3 = (unsigned long long )tmp___4;
    tmp___5 = XXH_readLE64((void const   *)(state->mem64 + 3), endian);
    tmp___6 = XXH64_round((U64 )state->v4, tmp___5);
    state->v4 = (unsigned long long )tmp___6;
    p += 32U - state->memsize;
    state->memsize = 0U;
  }
  if ((unsigned long )(p + 32) <= (unsigned long )bEnd) {
    limit = bEnd - 32;
    v1 = (U64 )state->v1;
    v2 = (U64 )state->v2;
    v3 = (U64 )state->v3;
    v4 = (U64 )state->v4;
    while (1) {
      tmp___7 = XXH_readLE64((void const   *)p, endian);
      v1 = XXH64_round(v1, tmp___7);
      p += 8;
      tmp___8 = XXH_readLE64((void const   *)p, endian);
      v2 = XXH64_round(v2, tmp___8);
      p += 8;
      tmp___9 = XXH_readLE64((void const   *)p, endian);
      v3 = XXH64_round(v3, tmp___9);
      p += 8;
      tmp___10 = XXH_readLE64((void const   *)p, endian);
      v4 = XXH64_round(v4, tmp___10);
      p += 8;
      if (! ((unsigned long )p <= (unsigned long )limit)) {
        break;
      }
    }
    state->v1 = (unsigned long long )v1;
    state->v2 = (unsigned long long )v2;
    state->v3 = (unsigned long long )v3;
    state->v4 = (unsigned long long )v4;
  }
  if ((unsigned long )p < (unsigned long )bEnd) {
    XXH_memcpy((void *)(state->mem64), (void const   *)p, (size_t )(bEnd - p));
    state->memsize = (unsigned int )(bEnd - p);
  }
  return ((XXH_errorcode )0);
}
}
__inline static U32 ( __attribute__((__always_inline__)) XXH32_digest_endian)(XXH32_state_t const   *state ,
                                                                              XXH_endianess endian ) 
{ 
  BYTE const   *p ;
  BYTE const   *bEnd ;
  U32 h32 ;
  U32 tmp ;

  {
  p = (BYTE const   *)(state->mem32);
  bEnd = (BYTE const   *)(state->mem32) + state->memsize;
  if (state->large_len) {
    h32 = (U32 )(((((state->v1 << 1) | (state->v1 >> 31)) + ((state->v2 << 7) | (state->v2 >> 25))) + ((state->v3 << 12) | (state->v3 >> 20))) + ((state->v4 << 18) | (state->v4 >> 14)));
  } else {
    h32 = (U32 )(state->v3 + PRIME32_5);
  }
  h32 += (U32 )state->total_len_32;
  while ((unsigned long )(p + 4) <= (unsigned long )bEnd) {
    tmp = XXH_readLE32((void const   *)p, endian);
    h32 += tmp * (U32 )PRIME32_3;
    h32 = ((h32 << 17) | (h32 >> 15)) * (unsigned int )PRIME32_4;
    p += 4;
  }
  while ((unsigned long )p < (unsigned long )bEnd) {
    h32 += (U32 )((unsigned int const   )*p * PRIME32_5);
    h32 = ((h32 << 11) | (h32 >> 21)) * (unsigned int )PRIME32_1;
    p ++;
  }
  h32 ^= h32 >> 15;
  h32 *= (U32 )PRIME32_2;
  h32 ^= h32 >> 13;
  h32 *= (U32 )PRIME32_3;
  h32 ^= h32 >> 16;
  return (h32);
}
}
XXH32_hash_t XXH32_hashFromCanonical(XXH32_canonical_t const   *src ) 
{ 
  U32 tmp ;

  {
  tmp = XXH_readBE32((void const   *)src);
  return (tmp);
}
}
void XXH32_canonicalFromHash(XXH32_canonical_t *dst , XXH32_hash_t hash ) 
{ 
  int tmp ;

  {
  if (*((char const   *)(& g_one))) {
    tmp = __builtin_bswap32((int )hash);
    hash = (XXH32_hash_t )tmp;
  }
  memcpy((void */* __restrict  */)dst, (void const   */* __restrict  */)(& hash),
         sizeof(*dst));
  return;
}
}
unsigned long long XXH64(void const   *input , size_t len , unsigned long long seed ) 
{ 
  XXH_endianess endian_detected ;
  U64 tmp___1 ;
  U64 tmp___2 ;

  {
  endian_detected = (XXH_endianess )*((char const   *)(& g_one));
  if ((unsigned int )endian_detected == 1U) {
    tmp___1 = XXH64_endian_align(input, len, (U64 )seed, (XXH_endianess )1, (XXH_alignment )1);
    return ((unsigned long long )tmp___1);
  } else {
    tmp___2 = XXH64_endian_align(input, len, (U64 )seed, (XXH_endianess )0, (XXH_alignment )1);
    return ((unsigned long long )tmp___2);
  }
}
}
__inline static U32 ( __attribute__((__always_inline__)) XXH_readLE32_align)(void const   *ptr ,
                                                                             XXH_endianess endian ,
                                                                             XXH_alignment align ) 
{ 
  U32 tmp ;
  U32 tmp___0 ;
  int tmp___1 ;
  U32 tmp___2 ;
  int tmp___3 ;
  U32 tmp___4 ;

  {
  if ((unsigned int )align == 1U) {
    if ((unsigned int )endian == 1U) {
      tmp = XXH_read32(ptr);
      tmp___2 = tmp;
    } else {
      tmp___0 = XXH_read32(ptr);
      tmp___1 = __builtin_bswap32((int )tmp___0);
      tmp___2 = (U32 )tmp___1;
    }
    return (tmp___2);
  } else {
    if ((unsigned int )endian == 1U) {
      tmp___4 = *((U32 const   *)ptr);
    } else {
      tmp___3 = __builtin_bswap32((int )*((U32 const   *)ptr));
      tmp___4 = (U32 const   )tmp___3;
    }
    return ((U32 )tmp___4);
  }
}
}
void PRIME32_5_i$nit(void) 
{ 


  {
  PRIME32_5 = (U32 const   )374761393U;
}
}
void XXH64_canonicalFromHash(XXH64_canonical_t *dst , XXH64_hash_t hash ) 
{ 
  long tmp ;

  {
  if (*((char const   *)(& g_one))) {
    tmp = __builtin_bswap64((long )hash);
    hash = (XXH64_hash_t )tmp;
  }
  memcpy((void */* __restrict  */)dst, (void const   */* __restrict  */)(& hash),
         sizeof(*dst));
  return;
}
}
__inline static U64 ( __attribute__((__always_inline__)) XXH64_digest_endian)(XXH64_state_t const   *state ,
                                                                              XXH_endianess endian ) 
{ 
  BYTE const   *p ;
  BYTE const   *bEnd ;
  U64 h64 ;
  U64 v1 ;
  U64 v2 ;
  U64 v3 ;
  U64 v4 ;
  U64 k1 ;
  U64 tmp ;
  U64 tmp___0 ;
  U32 tmp___1 ;

  {
  p = (BYTE const   *)(state->mem64);
  bEnd = (BYTE const   *)(state->mem64) + state->memsize;
  if (state->total_len >= 32ULL) {
    v1 = (U64 )state->v1;
    v2 = (U64 )state->v2;
    v3 = (U64 )state->v3;
    v4 = (U64 )state->v4;
    h64 = ((((v1 << 1) | (v1 >> 63)) + ((v2 << 7) | (v2 >> 57))) + ((v3 << 12) | (v3 >> 52))) + ((v4 << 18) | (v4 >> 46));
    h64 = XXH64_mergeRound(h64, v1);
    h64 = XXH64_mergeRound(h64, v2);
    h64 = XXH64_mergeRound(h64, v3);
    h64 = XXH64_mergeRound(h64, v4);
  } else {
    h64 = (U64 )(state->v3 + (unsigned long long const   )PRIME64_5);
  }
  h64 += (U64 )state->total_len;
  while ((unsigned long )(p + 8) <= (unsigned long )bEnd) {
    tmp = XXH_readLE64((void const   *)p, endian);
    tmp___0 = XXH64_round((U64 )0, tmp);
    k1 = tmp___0;
    h64 ^= k1;
    h64 = ((h64 << 27) | (h64 >> 37)) * (unsigned long )PRIME64_1 + (unsigned long )PRIME64_4;
    p += 8;
  }
  if ((unsigned long )(p + 4) <= (unsigned long )bEnd) {
    tmp___1 = XXH_readLE32((void const   *)p, endian);
    h64 ^= (U64 )tmp___1 * (U64 )PRIME64_1;
    h64 = ((h64 << 23) | (h64 >> 41)) * (unsigned long )PRIME64_2 + (unsigned long )PRIME64_3;
    p += 4;
  }
  while ((unsigned long )p < (unsigned long )bEnd) {
    h64 ^= (unsigned long )((unsigned long const   )*p * PRIME64_5);
    h64 = ((h64 << 11) | (h64 >> 53)) * (unsigned long )PRIME64_1;
    p ++;
  }
  h64 ^= h64 >> 33;
  h64 *= (U64 )PRIME64_2;
  h64 ^= h64 >> 29;
  h64 *= (U64 )PRIME64_3;
  h64 ^= h64 >> 32;
  return (h64);
}
}
XXH_errorcode XXH64_freeState(XXH64_state_t *statePtr ) 
{ 


  {
  XXH_free((void *)statePtr);
  return ((XXH_errorcode )0);
}
}
void PRIME64_4_i$nit(void) 
{ 


  {
  PRIME64_4 = (U64 const   )0x85ebca77c2b2ae63ULL;
}
}
XXH32_state_t *XXH32_createState(void) 
{ 
  void *tmp ;

  {
  tmp = XXH_malloc(sizeof(XXH32_state_t ));
  return ((XXH32_state_t *)tmp);
}
}
void PRIME64_5_i$nit(void) 
{ 


  {
  PRIME64_5 = (U64 const   )2870177450012600261ULL;
}
}
void PRIME64_1_i$nit(void) 
{ 


  {
  PRIME64_1 = (U64 const   )0x9e3779b185ebca87ULL;
}
}
__inline static XXH_errorcode ( __attribute__((__always_inline__)) XXH32_update_endian)(XXH32_state_t *state ,
                                                                                        void const   *input ,
                                                                                        size_t len ,
                                                                                        XXH_endianess endian ) 
{ 
  BYTE const   *p ;
  BYTE const   *bEnd ;
  U32 const   *p32 ;
  U32 tmp ;
  U32 tmp___0 ;
  U32 tmp___1 ;
  U32 tmp___2 ;
  BYTE const   *limit ;
  U32 v1 ;
  U32 v2 ;
  U32 v3 ;
  U32 v4 ;
  U32 tmp___3 ;
  U32 tmp___4 ;
  U32 tmp___5 ;
  U32 tmp___6 ;

  {
  p = (BYTE const   *)input;
  bEnd = p + len;
  if ((unsigned long )input == (unsigned long )((void *)0)) {
    return ((XXH_errorcode )1);
  }
  state->total_len_32 += (unsigned int )len;
  state->large_len |= (unsigned int )((len >= 16UL) | (state->total_len_32 >= 16U));
  if ((size_t )state->memsize + len < 16UL) {
    XXH_memcpy((void *)((BYTE *)(state->mem32) + state->memsize), input, len);
    state->memsize += (unsigned int )len;
    return ((XXH_errorcode )0);
  }
  if (state->memsize) {
    XXH_memcpy((void *)((BYTE *)(state->mem32) + state->memsize), input, (size_t )(16U - state->memsize));
    p32 = (U32 const   *)(state->mem32);
    tmp = XXH_readLE32((void const   *)p32, endian);
    state->v1 = XXH32_round(state->v1, tmp);
    p32 ++;
    tmp___0 = XXH_readLE32((void const   *)p32, endian);
    state->v2 = XXH32_round(state->v2, tmp___0);
    p32 ++;
    tmp___1 = XXH_readLE32((void const   *)p32, endian);
    state->v3 = XXH32_round(state->v3, tmp___1);
    p32 ++;
    tmp___2 = XXH_readLE32((void const   *)p32, endian);
    state->v4 = XXH32_round(state->v4, tmp___2);
    p += 16U - state->memsize;
    state->memsize = 0U;
  }
  if ((unsigned long )p <= (unsigned long )(bEnd - 16)) {
    limit = bEnd - 16;
    v1 = state->v1;
    v2 = state->v2;
    v3 = state->v3;
    v4 = state->v4;
    while (1) {
      tmp___3 = XXH_readLE32((void const   *)p, endian);
      v1 = XXH32_round(v1, tmp___3);
      p += 4;
      tmp___4 = XXH_readLE32((void const   *)p, endian);
      v2 = XXH32_round(v2, tmp___4);
      p += 4;
      tmp___5 = XXH_readLE32((void const   *)p, endian);
      v3 = XXH32_round(v3, tmp___5);
      p += 4;
      tmp___6 = XXH_readLE32((void const   *)p, endian);
      v4 = XXH32_round(v4, tmp___6);
      p += 4;
      if (! ((unsigned long )p <= (unsigned long )limit)) {
        break;
      }
    }
    state->v1 = v1;
    state->v2 = v2;
    state->v3 = v3;
    state->v4 = v4;
  }
  if ((unsigned long )p < (unsigned long )bEnd) {
    XXH_memcpy((void *)(state->mem32), (void const   *)p, (size_t )(bEnd - p));
    state->memsize = (unsigned int )(bEnd - p);
  }
  return ((XXH_errorcode )0);
}
}
void PRIME32_3_i$nit(void) 
{ 


  {
  PRIME32_3 = (U32 const   )3266489917U;
}
}
void XXH32_copyState(XXH32_state_t *dstState , XXH32_state_t const   *srcState ) 
{ 


  {
  memcpy((void */* __restrict  */)dstState, (void const   */* __restrict  */)srcState,
         sizeof(*dstState));
  return;
}
}
__inline static U64 ( __attribute__((__always_inline__)) XXH64_endian_align)(void const   *input ,
                                                                             size_t len ,
                                                                             U64 seed ,
                                                                             XXH_endianess endian ,
                                                                             XXH_alignment align ) 
{ 
  BYTE const   *p ;
  BYTE const   *bEnd ;
  U64 h64 ;
  BYTE const   *limit ;
  U64 v1 ;
  U64 v2 ;
  U64 v3 ;
  U64 v4 ;
  U64 tmp ;
  U64 tmp___0 ;
  U64 tmp___1 ;
  U64 tmp___2 ;
  U64 k1 ;
  U64 tmp___3 ;
  U64 tmp___4 ;
  U32 tmp___5 ;

  {
  p = (BYTE const   *)input;
  bEnd = p + len;
  if (len >= 32UL) {
    limit = bEnd - 32;
    v1 = (seed + (U64 )PRIME64_1) + (U64 )PRIME64_2;
    v2 = seed + (U64 )PRIME64_2;
    v3 = seed;
    v4 = seed - (U64 )PRIME64_1;
    while (1) {
      tmp = XXH_readLE64_align((void const   *)p, endian, align);
      v1 = XXH64_round(v1, tmp);
      p += 8;
      tmp___0 = XXH_readLE64_align((void const   *)p, endian, align);
      v2 = XXH64_round(v2, tmp___0);
      p += 8;
      tmp___1 = XXH_readLE64_align((void const   *)p, endian, align);
      v3 = XXH64_round(v3, tmp___1);
      p += 8;
      tmp___2 = XXH_readLE64_align((void const   *)p, endian, align);
      v4 = XXH64_round(v4, tmp___2);
      p += 8;
      if (! ((unsigned long )p <= (unsigned long )limit)) {
        break;
      }
    }
    h64 = ((((v1 << 1) | (v1 >> 63)) + ((v2 << 7) | (v2 >> 57))) + ((v3 << 12) | (v3 >> 52))) + ((v4 << 18) | (v4 >> 46));
    h64 = XXH64_mergeRound(h64, v1);
    h64 = XXH64_mergeRound(h64, v2);
    h64 = XXH64_mergeRound(h64, v3);
    h64 = XXH64_mergeRound(h64, v4);
  } else {
    h64 = seed + (U64 )PRIME64_5;
  }
  h64 += len;
  while ((unsigned long )(p + 8) <= (unsigned long )bEnd) {
    tmp___3 = XXH_readLE64_align((void const   *)p, endian, align);
    tmp___4 = XXH64_round((U64 )0, tmp___3);
    k1 = tmp___4;
    h64 ^= k1;
    h64 = ((h64 << 27) | (h64 >> 37)) * (unsigned long )PRIME64_1 + (unsigned long )PRIME64_4;
    p += 8;
  }
  if ((unsigned long )(p + 4) <= (unsigned long )bEnd) {
    tmp___5 = XXH_readLE32_align((void const   *)p, endian, align);
    h64 ^= (U64 )tmp___5 * (U64 )PRIME64_1;
    h64 = ((h64 << 23) | (h64 >> 41)) * (unsigned long )PRIME64_2 + (unsigned long )PRIME64_3;
    p += 4;
  }
  while ((unsigned long )p < (unsigned long )bEnd) {
    h64 ^= (unsigned long )((unsigned long const   )*p * PRIME64_5);
    h64 = ((h64 << 11) | (h64 >> 53)) * (unsigned long )PRIME64_1;
    p ++;
  }
  h64 ^= h64 >> 33;
  h64 *= (U64 )PRIME64_2;
  h64 ^= h64 >> 29;
  h64 *= (U64 )PRIME64_3;
  h64 ^= h64 >> 32;
  return (h64);
}
}
static U64 XXH64_mergeRound(U64 acc , U64 val ) 
{ 


  {
  val = XXH64_round((U64 )0, val);
  acc ^= val;
  acc = acc * (U64 )PRIME64_1 + (U64 )PRIME64_4;
  return (acc);
}
}
void PRIME32_1_i$nit(void) 
{ 


  {
  PRIME32_1 = (U32 const   )2654435761U;
}
}
void g_one_i$nit(void) 
{ 


  {
  g_one = (int const   )1;
}
}
int main(int argc , char **argv ) 
{ 
  char _1_main_$locals[128] ;
  union _1_main_$node _1_main_$stack[1][32] ;
  union _1_main_$node *_1_main_$sp[1] ;
  unsigned char *_1_main_$pc[1] ;

  {
  megaInit();
  _1_main_$sp[0] = _1_main_$stack[0];
  _1_main_$pc[0] = _1_main_$array[0];
  while (1) {
    switch (*(_1_main_$pc[0])) {
    case _1_main__constant_int$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_int = *((int *)_1_main_$pc[0]);
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__load_void_star$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_void_star = *((void **)(_1_main_$sp[0] + 0)->_void_star);
    break;
    case _1_main__convert_int2void_star$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_void_star = (void *)(_1_main_$sp[0] + 0)->_int;
    break;
    case _1_main__call$func_LIT_0: 
    (_1_main_$pc[0]) ++;
    switch (*((int *)_1_main_$pc[0])) {
    case 3: 
    *((unsigned long *)(_1_main_$locals + 88)) = SECRET(*((unsigned long *)(_1_main_$locals + 72)));
    break;
    case 4: 
    printf(*((char const   * __restrict  *)(_1_main_$locals + 104)), *((unsigned long *)(_1_main_$locals + 112)));
    break;
    case 5: 
    printf(*((char const   * __restrict  *)(_1_main_$locals + 120)));
    break;
    case 1: 
    printf(*((char const   * __restrict  *)(_1_main_$locals + 16)));
    break;
    case 2: 
    *((unsigned long *)(_1_main_$locals + 56)) = strtoul(*((char const   * __restrict  *)(_1_main_$locals + 24)),
                                                         *((char ** __restrict  *)(_1_main_$locals + 32)),
                                                         *((int *)(_1_main_$locals + 40)));
    break;
    }
    _1_main_$pc[0] += 4;
    break;
    case _1_main__Eq_unsigned_long_unsigned_long2int$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_int = (_1_main_$sp[0] + 0)->_unsigned_long == (_1_main_$sp[0] + -1)->_unsigned_long;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_unsigned_long = (_1_main_$sp[0] + 0)->_unsigned_long * (_1_main_$sp[0] + -1)->_unsigned_long;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__local$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_void_star = (void *)(_1_main_$locals + *((int *)_1_main_$pc[0]));
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__IndexPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_void_star = (_1_main_$sp[0] + 0)->_void_star + (_1_main_$sp[0] + -1)->_unsigned_long;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__formal$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    switch (*((int *)_1_main_$pc[0])) {
    case 1: 
    (_1_main_$sp[0] + 1)->_void_star = (void *)(& argv);
    break;
    case 0: 
    (_1_main_$sp[0] + 1)->_void_star = (void *)(& argc);
    break;
    }
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__load_int$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_int = *((int *)(_1_main_$sp[0] + 0)->_void_star);
    break;
    case _1_main__convert_int2unsigned_long$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_unsigned_long = (unsigned long )(_1_main_$sp[0] + 0)->_int;
    break;
    case _1_main__goto$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    _1_main_$pc[0] += *((int *)_1_main_$pc[0]);
    break;
    case _1_main__load_unsigned_long$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_unsigned_long = *((unsigned long *)(_1_main_$sp[0] + 0)->_void_star);
    break;
    case _1_main__store_void_star$left_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    *((void **)(_1_main_$sp[0] + 0)->_void_star) = (_1_main_$sp[0] + -1)->_void_star;
    _1_main_$sp[0] += -2;
    break;
    case _1_main__store_int$left_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    *((int *)(_1_main_$sp[0] + 0)->_void_star) = (_1_main_$sp[0] + -1)->_int;
    _1_main_$sp[0] += -2;
    break;
    case _1_main__convert_void_star2void_star$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_void_star = (_1_main_$sp[0] + 0)->_void_star;
    break;
    case _1_main__label$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    break;
    case _1_main__Lt_int_int2int$right_STA_0$result_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_int = (_1_main_$sp[0] + -1)->_int < (_1_main_$sp[0] + 0)->_int;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__constant_unsigned_long$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_unsigned_long = *((unsigned long *)_1_main_$pc[0]);
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 8;
    break;
    case _1_main__string$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_void_star = (void *)(_1_main_$strings + *((int *)_1_main_$pc[0]));
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__store_unsigned_long$right_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    *((unsigned long *)(_1_main_$sp[0] + -1)->_void_star) = (_1_main_$sp[0] + 0)->_unsigned_long;
    _1_main_$sp[0] += -2;
    break;
    case _1_main__branchIfTrue$expr_STA_0$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    if ((_1_main_$sp[0] + 0)->_int) {
      _1_main_$pc[0] += *((int *)_1_main_$pc[0]);
    } else {
      _1_main_$pc[0] += 4;
    }
    (_1_main_$sp[0]) --;
    break;
    case _1_main__return_int$expr_STA_0: 
    (_1_main_$pc[0]) ++;
    return ((_1_main_$sp[0] + 0)->_int);
    break;
    }
  }
}
}
unsigned long long XXH64_digest(XXH64_state_t const   *state_in ) 
{ 
  XXH_endianess endian_detected ;
  U64 tmp ;
  U64 tmp___0 ;

  {
  endian_detected = (XXH_endianess )*((char const   *)(& g_one));
  if ((unsigned int )endian_detected == 1U) {
    tmp = XXH64_digest_endian(state_in, (XXH_endianess )1);
    return ((unsigned long long )tmp);
  } else {
    tmp___0 = XXH64_digest_endian(state_in, (XXH_endianess )0);
    return ((unsigned long long )tmp___0);
  }
}
}
void XXH64_copyState(XXH64_state_t *dstState , XXH64_state_t const   *srcState ) 
{ 


  {
  memcpy((void */* __restrict  */)dstState, (void const   */* __restrict  */)srcState,
         sizeof(*dstState));
  return;
}
}
XXH_errorcode XXH64_reset(XXH64_state_t *statePtr , unsigned long long seed ) 
{ 
  XXH64_state_t state ;

  {
  memset((void *)(& state), 0, sizeof(state));
  state.v1 = (seed + (unsigned long long )PRIME64_1) + (unsigned long long )PRIME64_2;
  state.v2 = seed + (unsigned long long )PRIME64_2;
  state.v3 = seed;
  state.v4 = seed - (unsigned long long )PRIME64_1;
  memcpy((void */* __restrict  */)statePtr, (void const   */* __restrict  */)(& state),
         sizeof(state) - sizeof(state.reserved));
  return ((XXH_errorcode )0);
}
}
static void XXH_free(void *p ) 
{ 


  {
  free(p);
  return;
}
}
__inline static U64 ( __attribute__((__always_inline__)) XXH_readLE64_align)(void const   *ptr ,
                                                                             XXH_endianess endian ,
                                                                             XXH_alignment align ) 
{ 
  U64 tmp ;
  U64 tmp___0 ;
  long tmp___1 ;
  U64 tmp___2 ;
  long tmp___3 ;
  U64 tmp___4 ;

  {
  if ((unsigned int )align == 1U) {
    if ((unsigned int )endian == 1U) {
      tmp = XXH_read64(ptr);
      tmp___2 = tmp;
    } else {
      tmp___0 = XXH_read64(ptr);
      tmp___1 = __builtin_bswap64((long )tmp___0);
      tmp___2 = (U64 )tmp___1;
    }
    return (tmp___2);
  } else {
    if ((unsigned int )endian == 1U) {
      tmp___4 = *((U64 const   *)ptr);
    } else {
      tmp___3 = __builtin_bswap64((long )*((U64 const   *)ptr));
      tmp___4 = (U64 const   )tmp___3;
    }
    return ((U64 )tmp___4);
  }
}
}
static void *XXH_memcpy(void *dest , void const   *src , size_t size ) 
{ 
  void *tmp ;

  {
  tmp = memcpy((void */* __restrict  */)dest, (void const   */* __restrict  */)src,
               size);
  return (tmp);
}
}
void PRIME32_2_i$nit(void) 
{ 


  {
  PRIME32_2 = (U32 const   )2246822519U;
}
}
__inline static U32 ( __attribute__((__always_inline__)) XXH_readLE32)(void const   *ptr ,
                                                                       XXH_endianess endian ) 
{ 
  U32 tmp ;

  {
  tmp = XXH_readLE32_align(ptr, endian, (XXH_alignment )1);
  return (tmp);
}
}
static U32 XXH32_round(U32 seed , U32 input ) 
{ 


  {
  seed += input * (U32 )PRIME32_2;
  seed = (seed << 13) | (seed >> 19);
  seed *= (U32 )PRIME32_1;
  return (seed);
}
}
void PRIME64_2_i$nit(void) 
{ 


  {
  PRIME64_2 = (U64 const   )0xc2b2ae3d27d4eb4fULL;
}
}
unsigned int XXH32(void const   *input , size_t len , unsigned int seed ) 
{ 
  XXH_endianess endian_detected ;
  U32 tmp___1 ;
  U32 tmp___2 ;

  {
  endian_detected = (XXH_endianess )*((char const   *)(& g_one));
  if ((unsigned int )endian_detected == 1U) {
    tmp___1 = XXH32_endian_align(input, len, seed, (XXH_endianess )1, (XXH_alignment )1);
    return (tmp___1);
  } else {
    tmp___2 = XXH32_endian_align(input, len, seed, (XXH_endianess )0, (XXH_alignment )1);
    return (tmp___2);
  }
}
}
void PRIME64_3_i$nit(void) 
{ 


  {
  PRIME64_3 = (U64 const   )1609587929392839161ULL;
}
}
XXH_errorcode XXH32_update(XXH32_state_t *state_in , void const   *input , size_t len ) 
{ 
  XXH_endianess endian_detected ;
  XXH_errorcode tmp ;
  XXH_errorcode tmp___0 ;

  {
  endian_detected = (XXH_endianess )*((char const   *)(& g_one));
  if ((unsigned int )endian_detected == 1U) {
    tmp = XXH32_update_endian(state_in, input, len, (XXH_endianess )1);
    return (tmp);
  } else {
    tmp___0 = XXH32_update_endian(state_in, input, len, (XXH_endianess )0);
    return (tmp___0);
  }
}
}
static U32 XXH_readBE32(void const   *ptr ) 
{ 
  U32 tmp ;
  int tmp___0 ;
  U32 tmp___1 ;
  U32 tmp___2 ;

  {
  if (*((char const   *)(& g_one))) {
    tmp = XXH_read32(ptr);
    tmp___0 = __builtin_bswap32((int )tmp);
    tmp___2 = (U32 )tmp___0;
  } else {
    tmp___1 = XXH_read32(ptr);
    tmp___2 = tmp___1;
  }
  return (tmp___2);
}
}
__inline static U64 ( __attribute__((__always_inline__)) XXH_readLE64)(void const   *ptr ,
                                                                       XXH_endianess endian ) 
{ 
  U64 tmp ;

  {
  tmp = XXH_readLE64_align(ptr, endian, (XXH_alignment )1);
  return (tmp);
}
}
static void *XXH_malloc(size_t s ) 
{ 
  void *tmp ;

  {
  tmp = malloc(s);
  return (tmp);
}
}
void megaInit(void) 
{ 


  {
  g_one_i$nit();
  PRIME64_1_i$nit();
  PRIME64_2_i$nit();
  PRIME32_1_i$nit();
  PRIME64_3_i$nit();
  PRIME32_2_i$nit();
  PRIME64_4_i$nit();
  PRIME32_3_i$nit();
  PRIME64_5_i$nit();
  PRIME32_4_i$nit();
  PRIME32_5_i$nit();
}
}
