/* Generated by CIL v. 1.7.0 */
/* print_CIL_Input is false */

union _1_main_$node;
struct _IO_FILE;
union __anonunion_u_25;
enum _1_main_$op;
union __anonunion_u_26;
union __anonunion_u_27;
struct spooky_state;
struct timeval;
typedef unsigned long size_t;
typedef unsigned long __uint64_t;
typedef __uint64_t uint64_t;
void spooky_shorthash(void const   *message , size_t length , uint64_t *hash1 , uint64_t *hash2 ) ;
extern void exit(int status ) ;
typedef unsigned char __uint8_t;
typedef __uint8_t uint8_t;
__inline static uint64_t rot64(uint64_t x , int k ) ;
extern int fclose(void *stream ) ;
__inline static void mix(uint64_t const   *data , uint64_t *s0 , uint64_t *s1 , uint64_t *s2 ,
                         uint64_t *s3 , uint64_t *s4 , uint64_t *s5 , uint64_t *s6 ,
                         uint64_t *s7 , uint64_t *s8 , uint64_t *s9 , uint64_t *s10 ,
                         uint64_t *s11 ) ;
typedef unsigned long uintptr_t;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern  __attribute__((__nothrow__)) unsigned long ( __attribute__((__nonnull__(1),
__leaf__)) strtoul)(char const   * __restrict  __nptr , char ** __restrict  __endptr ,
                    int __base ) ;
extern int raise(int sig ) ;
extern void abort() ;
char const   *_1_main_$strings  =    "Call this program with 1 arguments\n\000%lu\n\000Success!\n\000";
extern void *malloc(unsigned long size ) ;
void spooky_update(struct spooky_state *state , void const   *message , size_t length ) ;
__inline static void end(uint64_t *h0 , uint64_t *h1 , uint64_t *h2 , uint64_t *h3 ,
                         uint64_t *h4 , uint64_t *h5 , uint64_t *h6 , uint64_t *h7 ,
                         uint64_t *h8 , uint64_t *h9 , uint64_t *h10 , uint64_t *h11 ) ;
extern int rand() ;
void spooky_init(struct spooky_state *state , uint64_t seed1 , uint64_t seed2 ) ;
extern unsigned long strlen(char const   *s ) ;
int main(int argc , char **argv ) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
extern int gettimeofday(struct timeval *tv , void *tz  , ...) ;
void megaInit(void) ;
union __anonunion_u_27 {
   uint8_t const   *p8 ;
   uint64_t *p64 ;
   uintptr_t i ;
};
extern int printf(char const   * __restrict  __format  , ...) ;
union __anonunion_u_26 {
   uint8_t const   *p8 ;
   uint64_t *p64 ;
   size_t i ;
};
extern int scanf(char const   *format  , ...) ;
typedef unsigned int __uint32_t;
typedef __uint32_t uint32_t;
union __anonunion_u_25 {
   uint8_t const   *p8 ;
   uint32_t *p32 ;
   uint64_t *p64 ;
   size_t i ;
};
uint64_t SECRET(unsigned long input ) ;
void spooky_final(struct spooky_state *state , uint64_t *hash1 , uint64_t *hash2 ) ;
enum _1_main_$op {
    _1_main__local$result_STA_0$value_LIT_0 = 252,
    _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1 = 60,
    _1_main__label$label_LAB_0 = 85,
    _1_main__load_void_star$left_STA_0$result_STA_0 = 22,
    _1_main__convert_void_star2void_star$left_STA_0$result_STA_0 = 239,
    _1_main__convert_int2unsigned_long$left_STA_0$result_STA_0 = 108,
    _1_main__constant_unsigned_long$result_STA_0$value_LIT_0 = 125,
    _1_main__Eq_unsigned_long_unsigned_long2int$left_STA_0$result_STA_0$right_STA_1 = 94,
    _1_main__string$result_STA_0$value_LIT_0 = 235,
    _1_main__convert_int2void_star$left_STA_0$result_STA_0 = 137,
    _1_main__branchIfTrue$expr_STA_0$label_LAB_0 = 191,
    _1_main__IndexPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1 = 175,
    _1_main__return_int$expr_STA_0 = 34,
    _1_main__store_void_star$left_STA_0$right_STA_1 = 31,
    _1_main__Lt_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 214,
    _1_main__constant_int$result_STA_0$value_LIT_0 = 7,
    _1_main__store_unsigned_long$right_STA_0$left_STA_1 = 89,
    _1_main__load_unsigned_long$left_STA_0$result_STA_0 = 150,
    _1_main__formal$result_STA_0$value_LIT_0 = 254,
    _1_main__load_int$left_STA_0$result_STA_0 = 132,
    _1_main__call$func_LIT_0 = 58,
    _1_main__store_int$left_STA_0$right_STA_1 = 233,
    _1_main__goto$label_LAB_0 = 55
} ;
extern float strtof(char const   *str , char const   *endptr ) ;
unsigned char _1_main_$array[1][262]  = { {        _1_main__formal$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)2, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__Lt_int_int2int$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)32,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__string$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__convert_void_star2void_star$left_STA_0$result_STA_0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_void_star$left_STA_0$right_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__return_int$expr_STA_0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)8, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_main__formal$result_STA_0$value_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__load_void_star$left_STA_0$result_STA_0, 
            _1_main__IndexPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__load_void_star$left_STA_0$result_STA_0,        _1_main__convert_void_star2void_star$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)24,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_void_star$left_STA_0$right_STA_1,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__convert_int2void_star$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)32,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_void_star$left_STA_0$right_STA_1,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)10,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)40, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1, 
            _1_main__call$func_LIT_0,        (unsigned char)2,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)48,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)56, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__load_unsigned_long$left_STA_0$result_STA_0, 
            _1_main__store_unsigned_long$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)64,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)48, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__load_unsigned_long$left_STA_0$result_STA_0, 
            _1_main__store_unsigned_long$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)72,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)64, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__load_unsigned_long$left_STA_0$result_STA_0, 
            _1_main__store_unsigned_long$right_STA_0$left_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)3,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)80, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)88,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_unsigned_long$left_STA_0$result_STA_0,        _1_main__store_unsigned_long$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)96, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)80,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_unsigned_long$left_STA_0$result_STA_0,        _1_main__store_unsigned_long$right_STA_0$left_STA_1,        _1_main__string$result_STA_0$value_LIT_0,        (unsigned char)36, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__convert_void_star2void_star$left_STA_0$result_STA_0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)104,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_void_star$left_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)112, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)96,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_unsigned_long$left_STA_0$result_STA_0,        _1_main__store_unsigned_long$right_STA_0$left_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)28,        (unsigned char)218, 
            (unsigned char)202,        (unsigned char)52,        (unsigned char)59,        (unsigned char)210, 
            (unsigned char)82,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)96,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_unsigned_long$left_STA_0$result_STA_0,        _1_main__Eq_unsigned_long_unsigned_long2int$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)26,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__string$result_STA_0$value_LIT_0,        (unsigned char)41, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__convert_void_star2void_star$left_STA_0$result_STA_0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)120,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_void_star$left_STA_0$right_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)5, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__return_int$expr_STA_0}};
extern unsigned long strnlen(char const   *s ,
                             unsigned long maxlen ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
union _1_main_$node {
   void *_void_star ;
   unsigned long _unsigned_long ;
   int _int ;
};
extern void *fopen(char const   *filename , char const   *mode ) ;
void spooky_hash128(void const   *message , size_t length , uint64_t *hash1 , uint64_t *hash2 ) ;
__inline static void short_mix(uint64_t *h0 , uint64_t *h1 , uint64_t *h2 , uint64_t *h3 ) ;
extern void signal(int sig , void *func ) ;
typedef struct _IO_FILE FILE;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
__inline static void short_end(uint64_t *h0 , uint64_t *h1 , uint64_t *h2 , uint64_t *h3 ) ;
extern  __attribute__((__nothrow__)) void *( __attribute__((__nonnull__(1), __leaf__)) memset)(void *__s ,
                                                                                               int __c ,
                                                                                               size_t __n ) ;
uint64_t spooky_hash64(void const   *message , size_t length , uint64_t seed ) ;
struct spooky_state {
   uint64_t m_data[24] ;
   uint64_t m_state[12] ;
   size_t m_length ;
   unsigned char m_remainder ;
};
extern int strncmp(char const   *s1 , char const   *s2 , unsigned long maxlen ) ;
__inline static void endPartial(uint64_t *h0 , uint64_t *h1 , uint64_t *h2 , uint64_t *h3 ,
                                uint64_t *h4 , uint64_t *h5 , uint64_t *h6 , uint64_t *h7 ,
                                uint64_t *h8 , uint64_t *h9 , uint64_t *h10 , uint64_t *h11 ) ;
uint32_t spooky_hash32(void const   *message , size_t length , uint32_t seed ) ;
extern  __attribute__((__nothrow__)) void *( __attribute__((__nonnull__(1,2), __leaf__)) memcpy)(void * __restrict  __dest ,
                                                                                                 void const   * __restrict  __src ,
                                                                                                 size_t __n ) ;
uint32_t spooky_hash32(void const   *message , size_t length , uint32_t seed ) 
{ 
  uint64_t hash1 ;
  uint64_t hash2 ;

  {
  hash1 = (uint64_t )seed;
  hash2 = (uint64_t )seed;
  spooky_hash128(message, length, & hash1, & hash2);
  return ((uint32_t )hash1);
}
}
void spooky_hash128(void const   *message , size_t length , uint64_t *hash1 , uint64_t *hash2 ) 
{ 
  uint64_t h0 ;
  uint64_t h1 ;
  uint64_t h2 ;
  uint64_t h3 ;
  uint64_t h4 ;
  uint64_t h5 ;
  uint64_t h6 ;
  uint64_t h7 ;
  uint64_t h8 ;
  uint64_t h9 ;
  uint64_t h10 ;
  uint64_t h11 ;
  uint64_t buf[12] ;
  uint64_t *endp ;
  union __anonunion_u_27 u ;
  size_t remainder ;

  {
  if (length < 192UL) {
    spooky_shorthash(message, length, hash1, hash2);
    return;
  }
  h9 = *hash1;
  h6 = h9;
  h3 = h6;
  h0 = h3;
  h10 = *hash2;
  h7 = h10;
  h4 = h7;
  h1 = h4;
  h11 = (uint64_t )0xdeadbeefdeadbeefULL;
  h8 = h11;
  h5 = h8;
  h2 = h5;
  u.p8 = (uint8_t const   *)message;
  endp = u.p64 + (length / 96UL) * 12UL;
  while ((unsigned long )u.p64 < (unsigned long )endp) {
    mix((uint64_t const   *)u.p64, & h0, & h1, & h2, & h3, & h4, & h5, & h6, & h7,
        & h8, & h9, & h10, & h11);
    u.p64 += 12;
  }
  remainder = length - (size_t )((uint8_t const   *)endp - (uint8_t const   *)message);
  memcpy((void */* __restrict  */)(buf), (void const   */* __restrict  */)endp, remainder);
  memset((void *)((uint8_t *)(buf) + remainder), 0, 96UL - remainder);
  *((uint8_t *)(buf) + 95) = (uint8_t )remainder;
  end(& h0, & h1, & h2, & h3, & h4, & h5, & h6, & h7, & h8, & h9, & h10, & h11);
  *hash1 = h0;
  *hash2 = h1;
  return;
}
}
__inline static void mix(uint64_t const   *data , uint64_t *s0 , uint64_t *s1 , uint64_t *s2 ,
                         uint64_t *s3 , uint64_t *s4 , uint64_t *s5 , uint64_t *s6 ,
                         uint64_t *s7 , uint64_t *s8 , uint64_t *s9 , uint64_t *s10 ,
                         uint64_t *s11 ) 
{ 


  {
  *s0 += (uint64_t )*(data + 0);
  *s2 ^= *s10;
  *s11 ^= *s0;
  *s0 = rot64(*s0, 11);
  *s11 += *s1;
  *s1 += (uint64_t )*(data + 1);
  *s3 ^= *s11;
  *s0 ^= *s1;
  *s1 = rot64(*s1, 32);
  *s0 += *s2;
  *s2 += (uint64_t )*(data + 2);
  *s4 ^= *s0;
  *s1 ^= *s2;
  *s2 = rot64(*s2, 43);
  *s1 += *s3;
  *s3 += (uint64_t )*(data + 3);
  *s5 ^= *s1;
  *s2 ^= *s3;
  *s3 = rot64(*s3, 31);
  *s2 += *s4;
  *s4 += (uint64_t )*(data + 4);
  *s6 ^= *s2;
  *s3 ^= *s4;
  *s4 = rot64(*s4, 17);
  *s3 += *s5;
  *s5 += (uint64_t )*(data + 5);
  *s7 ^= *s3;
  *s4 ^= *s5;
  *s5 = rot64(*s5, 28);
  *s4 += *s6;
  *s6 += (uint64_t )*(data + 6);
  *s8 ^= *s4;
  *s5 ^= *s6;
  *s6 = rot64(*s6, 39);
  *s5 += *s7;
  *s7 += (uint64_t )*(data + 7);
  *s9 ^= *s5;
  *s6 ^= *s7;
  *s7 = rot64(*s7, 57);
  *s6 += *s8;
  *s8 += (uint64_t )*(data + 8);
  *s10 ^= *s6;
  *s7 ^= *s8;
  *s8 = rot64(*s8, 55);
  *s7 += *s9;
  *s9 += (uint64_t )*(data + 9);
  *s11 ^= *s7;
  *s8 ^= *s9;
  *s9 = rot64(*s9, 54);
  *s8 += *s10;
  *s10 += (uint64_t )*(data + 10);
  *s0 ^= *s8;
  *s9 ^= *s10;
  *s10 = rot64(*s10, 22);
  *s9 += *s11;
  *s11 += (uint64_t )*(data + 11);
  *s1 ^= *s9;
  *s10 ^= *s11;
  *s11 = rot64(*s11, 46);
  *s10 += *s0;
  return;
}
}
uint64_t SECRET(unsigned long input ) 
{ 
  uint64_t tmp ;

  {
  tmp = spooky_hash64((void const   *)((char const   *)(& input)), sizeof(input),
                      (uint64_t )4660);
  return (tmp);
}
}
__inline static void short_mix(uint64_t *h0 , uint64_t *h1 , uint64_t *h2 , uint64_t *h3 ) 
{ 


  {
  *h2 = rot64(*h2, 50);
  *h2 += *h3;
  *h0 ^= *h2;
  *h3 = rot64(*h3, 52);
  *h3 += *h0;
  *h1 ^= *h3;
  *h0 = rot64(*h0, 30);
  *h0 += *h1;
  *h2 ^= *h0;
  *h1 = rot64(*h1, 41);
  *h1 += *h2;
  *h3 ^= *h1;
  *h2 = rot64(*h2, 54);
  *h2 += *h3;
  *h0 ^= *h2;
  *h3 = rot64(*h3, 48);
  *h3 += *h0;
  *h1 ^= *h3;
  *h0 = rot64(*h0, 38);
  *h0 += *h1;
  *h2 ^= *h0;
  *h1 = rot64(*h1, 37);
  *h1 += *h2;
  *h3 ^= *h1;
  *h2 = rot64(*h2, 62);
  *h2 += *h3;
  *h0 ^= *h2;
  *h3 = rot64(*h3, 34);
  *h3 += *h0;
  *h1 ^= *h3;
  *h0 = rot64(*h0, 5);
  *h0 += *h1;
  *h2 ^= *h0;
  *h1 = rot64(*h1, 36);
  *h1 += *h2;
  *h3 ^= *h1;
  return;
}
}
__inline static void endPartial(uint64_t *h0 , uint64_t *h1 , uint64_t *h2 , uint64_t *h3 ,
                                uint64_t *h4 , uint64_t *h5 , uint64_t *h6 , uint64_t *h7 ,
                                uint64_t *h8 , uint64_t *h9 , uint64_t *h10 , uint64_t *h11 ) 
{ 


  {
  *h11 += *h1;
  *h2 ^= *h11;
  *h1 = rot64(*h1, 44);
  *h0 += *h2;
  *h3 ^= *h0;
  *h2 = rot64(*h2, 15);
  *h1 += *h3;
  *h4 ^= *h1;
  *h3 = rot64(*h3, 34);
  *h2 += *h4;
  *h5 ^= *h2;
  *h4 = rot64(*h4, 21);
  *h3 += *h5;
  *h6 ^= *h3;
  *h5 = rot64(*h5, 38);
  *h4 += *h6;
  *h7 ^= *h4;
  *h6 = rot64(*h6, 33);
  *h5 += *h7;
  *h8 ^= *h5;
  *h7 = rot64(*h7, 10);
  *h6 += *h8;
  *h9 ^= *h6;
  *h8 = rot64(*h8, 13);
  *h7 += *h9;
  *h10 ^= *h7;
  *h9 = rot64(*h9, 38);
  *h8 += *h10;
  *h11 ^= *h8;
  *h10 = rot64(*h10, 53);
  *h9 += *h11;
  *h0 ^= *h9;
  *h11 = rot64(*h11, 42);
  *h10 += *h0;
  *h1 ^= *h10;
  *h0 = rot64(*h0, 54);
  return;
}
}
__inline static uint64_t rot64(uint64_t x , int k ) 
{ 


  {
  return ((x << k) | (x >> (64 - k)));
}
}
int main(int argc , char **argv ) 
{ 
  char _1_main_$locals[128] ;
  union _1_main_$node _1_main_$stack[1][32] ;
  union _1_main_$node *_1_main_$sp[1] ;
  unsigned char *_1_main_$pc[1] ;

  {
  megaInit();
  _1_main_$sp[0] = _1_main_$stack[0];
  _1_main_$pc[0] = _1_main_$array[0];
  while (1) {
    switch (*(_1_main_$pc[0])) {
    case _1_main__constant_int$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_int = *((int *)_1_main_$pc[0]);
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__load_void_star$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_void_star = *((void **)(_1_main_$sp[0] + 0)->_void_star);
    break;
    case _1_main__convert_int2void_star$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_void_star = (void *)(_1_main_$sp[0] + 0)->_int;
    break;
    case _1_main__call$func_LIT_0: 
    (_1_main_$pc[0]) ++;
    switch (*((int *)_1_main_$pc[0])) {
    case 3: 
    *((unsigned long *)(_1_main_$locals + 88)) = SECRET(*((unsigned long *)(_1_main_$locals + 72)));
    break;
    case 1: 
    printf(*((char const   * __restrict  *)(_1_main_$locals + 16)));
    break;
    case 2: 
    *((unsigned long *)(_1_main_$locals + 56)) = strtoul(*((char const   * __restrict  *)(_1_main_$locals + 24)),
                                                         *((char ** __restrict  *)(_1_main_$locals + 32)),
                                                         *((int *)(_1_main_$locals + 40)));
    break;
    case 5: 
    printf(*((char const   * __restrict  *)(_1_main_$locals + 120)));
    break;
    case 4: 
    printf(*((char const   * __restrict  *)(_1_main_$locals + 104)), *((unsigned long *)(_1_main_$locals + 112)));
    break;
    }
    _1_main_$pc[0] += 4;
    break;
    case _1_main__Eq_unsigned_long_unsigned_long2int$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_int = (_1_main_$sp[0] + 0)->_unsigned_long == (_1_main_$sp[0] + -1)->_unsigned_long;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_unsigned_long = (_1_main_$sp[0] + 0)->_unsigned_long * (_1_main_$sp[0] + -1)->_unsigned_long;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__local$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_void_star = (void *)(_1_main_$locals + *((int *)_1_main_$pc[0]));
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__IndexPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_void_star = (_1_main_$sp[0] + 0)->_void_star + (_1_main_$sp[0] + -1)->_unsigned_long;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__formal$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    switch (*((int *)_1_main_$pc[0])) {
    case 1: 
    (_1_main_$sp[0] + 1)->_void_star = (void *)(& argv);
    break;
    case 0: 
    (_1_main_$sp[0] + 1)->_void_star = (void *)(& argc);
    break;
    }
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__load_int$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_int = *((int *)(_1_main_$sp[0] + 0)->_void_star);
    break;
    case _1_main__convert_int2unsigned_long$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_unsigned_long = (unsigned long )(_1_main_$sp[0] + 0)->_int;
    break;
    case _1_main__goto$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    _1_main_$pc[0] += *((int *)_1_main_$pc[0]);
    break;
    case _1_main__load_unsigned_long$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_unsigned_long = *((unsigned long *)(_1_main_$sp[0] + 0)->_void_star);
    break;
    case _1_main__store_void_star$left_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    *((void **)(_1_main_$sp[0] + 0)->_void_star) = (_1_main_$sp[0] + -1)->_void_star;
    _1_main_$sp[0] += -2;
    break;
    case _1_main__store_int$left_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    *((int *)(_1_main_$sp[0] + 0)->_void_star) = (_1_main_$sp[0] + -1)->_int;
    _1_main_$sp[0] += -2;
    break;
    case _1_main__convert_void_star2void_star$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_void_star = (_1_main_$sp[0] + 0)->_void_star;
    break;
    case _1_main__label$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    break;
    case _1_main__Lt_int_int2int$right_STA_0$result_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_int = (_1_main_$sp[0] + -1)->_int < (_1_main_$sp[0] + 0)->_int;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__constant_unsigned_long$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_unsigned_long = *((unsigned long *)_1_main_$pc[0]);
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 8;
    break;
    case _1_main__string$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_void_star = (void *)(_1_main_$strings + *((int *)_1_main_$pc[0]));
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__store_unsigned_long$right_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    *((unsigned long *)(_1_main_$sp[0] + -1)->_void_star) = (_1_main_$sp[0] + 0)->_unsigned_long;
    _1_main_$sp[0] += -2;
    break;
    case _1_main__branchIfTrue$expr_STA_0$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    if ((_1_main_$sp[0] + 0)->_int) {
      _1_main_$pc[0] += *((int *)_1_main_$pc[0]);
    } else {
      _1_main_$pc[0] += 4;
    }
    (_1_main_$sp[0]) --;
    break;
    case _1_main__return_int$expr_STA_0: 
    (_1_main_$pc[0]) ++;
    return ((_1_main_$sp[0] + 0)->_int);
    break;
    }
  }
}
}
__inline static void end(uint64_t *h0 , uint64_t *h1 , uint64_t *h2 , uint64_t *h3 ,
                         uint64_t *h4 , uint64_t *h5 , uint64_t *h6 , uint64_t *h7 ,
                         uint64_t *h8 , uint64_t *h9 , uint64_t *h10 , uint64_t *h11 ) 
{ 


  {
  endPartial(h0, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11);
  endPartial(h0, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11);
  endPartial(h0, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11);
  return;
}
}
__inline static void short_end(uint64_t *h0 , uint64_t *h1 , uint64_t *h2 , uint64_t *h3 ) 
{ 


  {
  *h3 ^= *h2;
  *h2 = rot64(*h2, 15);
  *h3 += *h2;
  *h0 ^= *h3;
  *h3 = rot64(*h3, 52);
  *h0 += *h3;
  *h1 ^= *h0;
  *h0 = rot64(*h0, 26);
  *h1 += *h0;
  *h2 ^= *h1;
  *h1 = rot64(*h1, 51);
  *h2 += *h1;
  *h3 ^= *h2;
  *h2 = rot64(*h2, 28);
  *h3 += *h2;
  *h0 ^= *h3;
  *h3 = rot64(*h3, 9);
  *h0 += *h3;
  *h1 ^= *h0;
  *h0 = rot64(*h0, 47);
  *h1 += *h0;
  *h2 ^= *h1;
  *h1 = rot64(*h1, 54);
  *h2 += *h1;
  *h3 ^= *h2;
  *h2 = rot64(*h2, 32);
  *h3 += *h2;
  *h0 ^= *h3;
  *h3 = rot64(*h3, 25);
  *h0 += *h3;
  *h1 ^= *h0;
  *h0 = rot64(*h0, 63);
  *h1 += *h0;
  return;
}
}
void spooky_init(struct spooky_state *state , uint64_t seed1 , uint64_t seed2 ) 
{ 


  {
  state->m_length = (size_t )0;
  state->m_remainder = (unsigned char)0;
  state->m_state[0] = seed1;
  state->m_state[1] = seed2;
  return;
}
}
void megaInit(void) 
{ 


  {

}
}
void spooky_shorthash(void const   *message , size_t length , uint64_t *hash1 , uint64_t *hash2 ) 
{ 
  union __anonunion_u_25 u ;
  size_t remainder ;
  uint64_t a ;
  uint64_t b ;
  uint64_t c ;
  uint64_t d ;
  uint64_t const   *endp ;

  {
  u.p8 = (uint8_t const   *)message;
  remainder = length % 32UL;
  a = *hash1;
  b = *hash2;
  c = (uint64_t )0xdeadbeefdeadbeefULL;
  d = (uint64_t )0xdeadbeefdeadbeefULL;
  if (length > 15UL) {
    endp = (uint64_t const   *)(u.p64 + (length / 32UL) * 4UL);
    while ((unsigned long )u.p64 < (unsigned long )endp) {
      c += *(u.p64 + 0);
      d += *(u.p64 + 1);
      short_mix(& a, & b, & c, & d);
      a += *(u.p64 + 2);
      b += *(u.p64 + 3);
      u.p64 += 4;
    }
    if (remainder >= 16UL) {
      c += *(u.p64 + 0);
      d += *(u.p64 + 1);
      short_mix(& a, & b, & c, & d);
      u.p64 += 2;
      remainder -= 16UL;
    }
  }
  d += length << 56;
  switch (remainder) {
  case 15UL: 
  d += (uint64_t )*(u.p8 + 14) << 48;
  case 14UL: 
  d += (uint64_t )*(u.p8 + 13) << 40;
  case 13UL: 
  d += (uint64_t )*(u.p8 + 12) << 32;
  case 12UL: 
  d += (uint64_t )*(u.p32 + 2);
  c += *(u.p64 + 0);
  break;
  case 11UL: 
  d += (uint64_t )*(u.p8 + 10) << 16;
  case 10UL: 
  d += (uint64_t )*(u.p8 + 9) << 8;
  case 9UL: 
  d += (uint64_t )*(u.p8 + 8);
  case 8UL: 
  c += *(u.p64 + 0);
  break;
  case 7UL: 
  c += (uint64_t )*(u.p8 + 6) << 48;
  case 6UL: 
  c += (uint64_t )*(u.p8 + 5) << 40;
  case 5UL: 
  c += (uint64_t )*(u.p8 + 4) << 32;
  case 4UL: 
  c += (uint64_t )*(u.p32 + 0);
  break;
  case 3UL: 
  c += (uint64_t )*(u.p8 + 2) << 16;
  case 2UL: 
  c += (uint64_t )*(u.p8 + 1) << 8;
  case 1UL: 
  c += (uint64_t )*(u.p8 + 0);
  break;
  case 0UL: 
  c = (uint64_t )((unsigned long long )c + 0xdeadbeefdeadbeefULL);
  d = (uint64_t )((unsigned long long )d + 0xdeadbeefdeadbeefULL);
  }
  short_end(& a, & b, & c, & d);
  *hash1 = a;
  *hash2 = b;
  return;
}
}
void spooky_update(struct spooky_state *state , void const   *message , size_t length ) 
{ 
  uint64_t h0 ;
  uint64_t h1 ;
  uint64_t h2 ;
  uint64_t h3 ;
  uint64_t h4 ;
  uint64_t h5 ;
  uint64_t h6 ;
  uint64_t h7 ;
  uint64_t h8 ;
  uint64_t h9 ;
  uint64_t h10 ;
  uint64_t h11 ;
  size_t newLength ;
  uint8_t remainder ;
  union __anonunion_u_26 u ;
  uint64_t const   *endp ;
  uint8_t prefix ;

  {
  newLength = length + (size_t )state->m_remainder;
  if (newLength < 192UL) {
    memcpy((void */* __restrict  */)((uint8_t *)(state->m_data) + state->m_remainder),
           (void const   */* __restrict  */)message, length);
    state->m_length = length + state->m_length;
    state->m_remainder = (uint8_t )newLength;
    return;
  }
  if (state->m_length < 192UL) {
    h9 = state->m_state[0];
    h6 = h9;
    h3 = h6;
    h0 = h3;
    h10 = state->m_state[1];
    h7 = h10;
    h4 = h7;
    h1 = h4;
    h11 = (uint64_t )0xdeadbeefdeadbeefULL;
    h8 = h11;
    h5 = h8;
    h2 = h5;
  } else {
    h0 = state->m_state[0];
    h1 = state->m_state[1];
    h2 = state->m_state[2];
    h3 = state->m_state[3];
    h4 = state->m_state[4];
    h5 = state->m_state[5];
    h6 = state->m_state[6];
    h7 = state->m_state[7];
    h8 = state->m_state[8];
    h9 = state->m_state[9];
    h10 = state->m_state[10];
    h11 = state->m_state[11];
  }
  state->m_length = length + state->m_length;
  if (state->m_remainder) {
    prefix = (uint8_t )(192 - (int )state->m_remainder);
    memcpy((void */* __restrict  */)((uint8_t *)(state->m_data) + state->m_remainder),
           (void const   */* __restrict  */)message, (size_t )prefix);
    u.p64 = state->m_data;
    mix((uint64_t const   *)u.p64, & h0, & h1, & h2, & h3, & h4, & h5, & h6, & h7,
        & h8, & h9, & h10, & h11);
    mix((uint64_t const   *)(u.p64 + 12), & h0, & h1, & h2, & h3, & h4, & h5, & h6,
        & h7, & h8, & h9, & h10, & h11);
    u.p8 = (uint8_t const   *)message + (int )prefix;
    length -= (size_t )prefix;
  } else {
    u.p8 = (uint8_t const   *)message;
  }
  endp = (uint64_t const   *)(u.p64 + (length / 96UL) * 12UL);
  remainder = (uint8_t )(length - (size_t )((uint8_t const   *)endp - u.p8));
  while ((unsigned long )u.p64 < (unsigned long )endp) {
    mix((uint64_t const   *)u.p64, & h0, & h1, & h2, & h3, & h4, & h5, & h6, & h7,
        & h8, & h9, & h10, & h11);
    u.p64 += 12;
  }
  state->m_remainder = remainder;
  memcpy((void */* __restrict  */)(state->m_data), (void const   */* __restrict  */)endp,
         (size_t )remainder);
  state->m_state[0] = h0;
  state->m_state[1] = h1;
  state->m_state[2] = h2;
  state->m_state[3] = h3;
  state->m_state[4] = h4;
  state->m_state[5] = h5;
  state->m_state[6] = h6;
  state->m_state[7] = h7;
  state->m_state[8] = h8;
  state->m_state[9] = h9;
  state->m_state[10] = h10;
  state->m_state[11] = h11;
  return;
}
}
void spooky_final(struct spooky_state *state , uint64_t *hash1 , uint64_t *hash2 ) 
{ 
  uint64_t h0 ;
  uint64_t h1 ;
  uint64_t h2 ;
  uint64_t h3 ;
  uint64_t h4 ;
  uint64_t h5 ;
  uint64_t h6 ;
  uint64_t h7 ;
  uint64_t h8 ;
  uint64_t h9 ;
  uint64_t h10 ;
  uint64_t h11 ;
  uint64_t const   *data ;
  uint8_t remainder ;

  {
  data = (uint64_t const   *)(state->m_data);
  remainder = state->m_remainder;
  if (state->m_length < 192UL) {
    spooky_shorthash((void const   *)(state->m_data), state->m_length, hash1, hash2);
    return;
  }
  h0 = state->m_state[0];
  h1 = state->m_state[1];
  h2 = state->m_state[2];
  h3 = state->m_state[3];
  h4 = state->m_state[4];
  h5 = state->m_state[5];
  h6 = state->m_state[6];
  h7 = state->m_state[7];
  h8 = state->m_state[8];
  h9 = state->m_state[9];
  h10 = state->m_state[10];
  h11 = state->m_state[11];
  if ((int )remainder >= 96) {
    mix(data, & h0, & h1, & h2, & h3, & h4, & h5, & h6, & h7, & h8, & h9, & h10, & h11);
    data += 12;
    remainder = (uint8_t )((int )remainder - 96);
  }
  memset((void *)((uint8_t *)data + remainder), 0, (size_t )(96 - (int )remainder));
  *((uint8_t *)data + 95) = remainder;
  mix(data, & h0, & h1, & h2, & h3, & h4, & h5, & h6, & h7, & h8, & h9, & h10, & h11);
  end(& h0, & h1, & h2, & h3, & h4, & h5, & h6, & h7, & h8, & h9, & h10, & h11);
  *hash1 = h0;
  *hash2 = h1;
  return;
}
}
uint64_t spooky_hash64(void const   *message , size_t length , uint64_t seed ) 
{ 
  uint64_t hash1 ;

  {
  hash1 = seed;
  spooky_hash128(message, length, & hash1, & seed);
  return (hash1);
}
}
